// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: odservice.proto

package kr.wise.advisor.prepare.outlier.grpc;

public interface ColResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kr.wise.advisor.prepare.outlier.ColResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string arrtnm = 1;</code>
   */
  java.lang.String getArrtnm();
  /**
   * <code>string arrtnm = 1;</code>
   */
  com.google.protobuf.ByteString
      getArrtnmBytes();

  /**
   * <code>string varId = 2;</code>
   */
  java.lang.String getVarId();
  /**
   * <code>string varId = 2;</code>
   */
  com.google.protobuf.ByteString
      getVarIdBytes();

  /**
   * <code>repeated float colval = 3;</code>
   */
  java.util.List<java.lang.Float> getColvalList();
  /**
   * <code>repeated float colval = 3;</code>
   */
  int getColvalCount();
  /**
   * <code>repeated float colval = 3;</code>
   */
  float getColval(int index);
}
