// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: odservice.proto

package kr.wise.advisor.prepare.outlier.grpc;

/**
 * Protobuf type {@code kr.wise.advisor.prepare.outlier.ColResponse}
 */
public  final class ColResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kr.wise.advisor.prepare.outlier.ColResponse)
    ColResponseOrBuilder {
  // Use ColResponse.newBuilder() to construct.
  private ColResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ColResponse() {
    arrtnm_ = "";
    varId_ = "";
    colval_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private ColResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            arrtnm_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            varId_ = s;
            break;
          }
          case 29: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              colval_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000004;
            }
            colval_.add(input.readFloat());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              colval_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              colval_.add(input.readFloat());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        colval_ = java.util.Collections.unmodifiableList(colval_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_ColResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_ColResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kr.wise.advisor.prepare.outlier.grpc.ColResponse.class, kr.wise.advisor.prepare.outlier.grpc.ColResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ARRTNM_FIELD_NUMBER = 1;
  private volatile java.lang.Object arrtnm_;
  /**
   * <code>string arrtnm = 1;</code>
   */
  public java.lang.String getArrtnm() {
    java.lang.Object ref = arrtnm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      arrtnm_ = s;
      return s;
    }
  }
  /**
   * <code>string arrtnm = 1;</code>
   */
  public com.google.protobuf.ByteString
      getArrtnmBytes() {
    java.lang.Object ref = arrtnm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      arrtnm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VARID_FIELD_NUMBER = 2;
  private volatile java.lang.Object varId_;
  /**
   * <code>string varId = 2;</code>
   */
  public java.lang.String getVarId() {
    java.lang.Object ref = varId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      varId_ = s;
      return s;
    }
  }
  /**
   * <code>string varId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getVarIdBytes() {
    java.lang.Object ref = varId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      varId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COLVAL_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Float> colval_;
  /**
   * <code>repeated float colval = 3;</code>
   */
  public java.util.List<java.lang.Float>
      getColvalList() {
    return colval_;
  }
  /**
   * <code>repeated float colval = 3;</code>
   */
  public int getColvalCount() {
    return colval_.size();
  }
  /**
   * <code>repeated float colval = 3;</code>
   */
  public float getColval(int index) {
    return colval_.get(index);
  }
  private int colvalMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getArrtnmBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, arrtnm_);
    }
    if (!getVarIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, varId_);
    }
    if (getColvalList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(colvalMemoizedSerializedSize);
    }
    for (int i = 0; i < colval_.size(); i++) {
      output.writeFloatNoTag(colval_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getArrtnmBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, arrtnm_);
    }
    if (!getVarIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, varId_);
    }
    {
      int dataSize = 0;
      dataSize = 4 * getColvalList().size();
      size += dataSize;
      if (!getColvalList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      colvalMemoizedSerializedSize = dataSize;
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kr.wise.advisor.prepare.outlier.grpc.ColResponse)) {
      return super.equals(obj);
    }
    kr.wise.advisor.prepare.outlier.grpc.ColResponse other = (kr.wise.advisor.prepare.outlier.grpc.ColResponse) obj;

    boolean result = true;
    result = result && getArrtnm()
        .equals(other.getArrtnm());
    result = result && getVarId()
        .equals(other.getVarId());
    result = result && getColvalList()
        .equals(other.getColvalList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ARRTNM_FIELD_NUMBER;
    hash = (53 * hash) + getArrtnm().hashCode();
    hash = (37 * hash) + VARID_FIELD_NUMBER;
    hash = (53 * hash) + getVarId().hashCode();
    if (getColvalCount() > 0) {
      hash = (37 * hash) + COLVAL_FIELD_NUMBER;
      hash = (53 * hash) + getColvalList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kr.wise.advisor.prepare.outlier.grpc.ColResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.ColResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.ColResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.ColResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.ColResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.ColResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.ColResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.ColResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.ColResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.ColResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.ColResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.ColResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kr.wise.advisor.prepare.outlier.grpc.ColResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kr.wise.advisor.prepare.outlier.ColResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kr.wise.advisor.prepare.outlier.ColResponse)
      kr.wise.advisor.prepare.outlier.grpc.ColResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_ColResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_ColResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kr.wise.advisor.prepare.outlier.grpc.ColResponse.class, kr.wise.advisor.prepare.outlier.grpc.ColResponse.Builder.class);
    }

    // Construct using kr.wise.advisor.prepare.outlier.grpc.ColResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      arrtnm_ = "";

      varId_ = "";

      colval_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_ColResponse_descriptor;
    }

    public kr.wise.advisor.prepare.outlier.grpc.ColResponse getDefaultInstanceForType() {
      return kr.wise.advisor.prepare.outlier.grpc.ColResponse.getDefaultInstance();
    }

    public kr.wise.advisor.prepare.outlier.grpc.ColResponse build() {
      kr.wise.advisor.prepare.outlier.grpc.ColResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kr.wise.advisor.prepare.outlier.grpc.ColResponse buildPartial() {
      kr.wise.advisor.prepare.outlier.grpc.ColResponse result = new kr.wise.advisor.prepare.outlier.grpc.ColResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.arrtnm_ = arrtnm_;
      result.varId_ = varId_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        colval_ = java.util.Collections.unmodifiableList(colval_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.colval_ = colval_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kr.wise.advisor.prepare.outlier.grpc.ColResponse) {
        return mergeFrom((kr.wise.advisor.prepare.outlier.grpc.ColResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kr.wise.advisor.prepare.outlier.grpc.ColResponse other) {
      if (other == kr.wise.advisor.prepare.outlier.grpc.ColResponse.getDefaultInstance()) return this;
      if (!other.getArrtnm().isEmpty()) {
        arrtnm_ = other.arrtnm_;
        onChanged();
      }
      if (!other.getVarId().isEmpty()) {
        varId_ = other.varId_;
        onChanged();
      }
      if (!other.colval_.isEmpty()) {
        if (colval_.isEmpty()) {
          colval_ = other.colval_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureColvalIsMutable();
          colval_.addAll(other.colval_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kr.wise.advisor.prepare.outlier.grpc.ColResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kr.wise.advisor.prepare.outlier.grpc.ColResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object arrtnm_ = "";
    /**
     * <code>string arrtnm = 1;</code>
     */
    public java.lang.String getArrtnm() {
      java.lang.Object ref = arrtnm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        arrtnm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string arrtnm = 1;</code>
     */
    public com.google.protobuf.ByteString
        getArrtnmBytes() {
      java.lang.Object ref = arrtnm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        arrtnm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string arrtnm = 1;</code>
     */
    public Builder setArrtnm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      arrtnm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string arrtnm = 1;</code>
     */
    public Builder clearArrtnm() {
      
      arrtnm_ = getDefaultInstance().getArrtnm();
      onChanged();
      return this;
    }
    /**
     * <code>string arrtnm = 1;</code>
     */
    public Builder setArrtnmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      arrtnm_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object varId_ = "";
    /**
     * <code>string varId = 2;</code>
     */
    public java.lang.String getVarId() {
      java.lang.Object ref = varId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        varId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string varId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVarIdBytes() {
      java.lang.Object ref = varId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        varId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string varId = 2;</code>
     */
    public Builder setVarId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      varId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string varId = 2;</code>
     */
    public Builder clearVarId() {
      
      varId_ = getDefaultInstance().getVarId();
      onChanged();
      return this;
    }
    /**
     * <code>string varId = 2;</code>
     */
    public Builder setVarIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      varId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Float> colval_ = java.util.Collections.emptyList();
    private void ensureColvalIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        colval_ = new java.util.ArrayList<java.lang.Float>(colval_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated float colval = 3;</code>
     */
    public java.util.List<java.lang.Float>
        getColvalList() {
      return java.util.Collections.unmodifiableList(colval_);
    }
    /**
     * <code>repeated float colval = 3;</code>
     */
    public int getColvalCount() {
      return colval_.size();
    }
    /**
     * <code>repeated float colval = 3;</code>
     */
    public float getColval(int index) {
      return colval_.get(index);
    }
    /**
     * <code>repeated float colval = 3;</code>
     */
    public Builder setColval(
        int index, float value) {
      ensureColvalIsMutable();
      colval_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float colval = 3;</code>
     */
    public Builder addColval(float value) {
      ensureColvalIsMutable();
      colval_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float colval = 3;</code>
     */
    public Builder addAllColval(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureColvalIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, colval_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float colval = 3;</code>
     */
    public Builder clearColval() {
      colval_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:kr.wise.advisor.prepare.outlier.ColResponse)
  }

  // @@protoc_insertion_point(class_scope:kr.wise.advisor.prepare.outlier.ColResponse)
  private static final kr.wise.advisor.prepare.outlier.grpc.ColResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kr.wise.advisor.prepare.outlier.grpc.ColResponse();
  }

  public static kr.wise.advisor.prepare.outlier.grpc.ColResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ColResponse>
      PARSER = new com.google.protobuf.AbstractParser<ColResponse>() {
    public ColResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new ColResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ColResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ColResponse> getParserForType() {
    return PARSER;
  }

  public kr.wise.advisor.prepare.outlier.grpc.ColResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

