// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: odservice.proto

package kr.wise.advisor.prepare.outlier.grpc;

/**
 * Protobuf type {@code kr.wise.advisor.prepare.outlier.OdResponse}
 */
public  final class OdResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kr.wise.advisor.prepare.outlier.OdResponse)
    OdResponseOrBuilder {
  // Use OdResponse.newBuilder() to construct.
  private OdResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OdResponse() {
    error_ = 0;
    results_ = java.util.Collections.emptyList();
    colres_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private OdResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            error_ = input.readInt32();
            break;
          }
          case 16: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              results_ = new java.util.ArrayList<java.lang.Boolean>();
              mutable_bitField0_ |= 0x00000002;
            }
            results_.add(input.readBool());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
              results_ = new java.util.ArrayList<java.lang.Boolean>();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              results_.add(input.readBool());
            }
            input.popLimit(limit);
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              colres_ = new java.util.ArrayList<kr.wise.advisor.prepare.outlier.grpc.ColResponse>();
              mutable_bitField0_ |= 0x00000004;
            }
            colres_.add(
                input.readMessage(kr.wise.advisor.prepare.outlier.grpc.ColResponse.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        results_ = java.util.Collections.unmodifiableList(results_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        colres_ = java.util.Collections.unmodifiableList(colres_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_OdResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_OdResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kr.wise.advisor.prepare.outlier.grpc.OdResponse.class, kr.wise.advisor.prepare.outlier.grpc.OdResponse.Builder.class);
  }

  private int bitField0_;
  public static final int ERROR_FIELD_NUMBER = 1;
  private int error_;
  /**
   * <pre>
   * -1 for no error, 0 for bad request, 1 for process error
   * </pre>
   *
   * <code>int32 error = 1;</code>
   */
  public int getError() {
    return error_;
  }

  public static final int RESULTS_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Boolean> results_;
  /**
   * <code>repeated bool results = 2;</code>
   */
  public java.util.List<java.lang.Boolean>
      getResultsList() {
    return results_;
  }
  /**
   * <code>repeated bool results = 2;</code>
   */
  public int getResultsCount() {
    return results_.size();
  }
  /**
   * <code>repeated bool results = 2;</code>
   */
  public boolean getResults(int index) {
    return results_.get(index);
  }
  private int resultsMemoizedSerializedSize = -1;

  public static final int COLRES_FIELD_NUMBER = 3;
  private java.util.List<kr.wise.advisor.prepare.outlier.grpc.ColResponse> colres_;
  /**
   * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
   */
  public java.util.List<kr.wise.advisor.prepare.outlier.grpc.ColResponse> getColresList() {
    return colres_;
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
   */
  public java.util.List<? extends kr.wise.advisor.prepare.outlier.grpc.ColResponseOrBuilder> 
      getColresOrBuilderList() {
    return colres_;
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
   */
  public int getColresCount() {
    return colres_.size();
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
   */
  public kr.wise.advisor.prepare.outlier.grpc.ColResponse getColres(int index) {
    return colres_.get(index);
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
   */
  public kr.wise.advisor.prepare.outlier.grpc.ColResponseOrBuilder getColresOrBuilder(
      int index) {
    return colres_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (error_ != 0) {
      output.writeInt32(1, error_);
    }
    if (getResultsList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(resultsMemoizedSerializedSize);
    }
    for (int i = 0; i < results_.size(); i++) {
      output.writeBoolNoTag(results_.get(i));
    }
    for (int i = 0; i < colres_.size(); i++) {
      output.writeMessage(3, colres_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (error_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, error_);
    }
    {
      int dataSize = 0;
      dataSize = 1 * getResultsList().size();
      size += dataSize;
      if (!getResultsList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      resultsMemoizedSerializedSize = dataSize;
    }
    for (int i = 0; i < colres_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, colres_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kr.wise.advisor.prepare.outlier.grpc.OdResponse)) {
      return super.equals(obj);
    }
    kr.wise.advisor.prepare.outlier.grpc.OdResponse other = (kr.wise.advisor.prepare.outlier.grpc.OdResponse) obj;

    boolean result = true;
    result = result && (getError()
        == other.getError());
    result = result && getResultsList()
        .equals(other.getResultsList());
    result = result && getColresList()
        .equals(other.getColresList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError();
    if (getResultsCount() > 0) {
      hash = (37 * hash) + RESULTS_FIELD_NUMBER;
      hash = (53 * hash) + getResultsList().hashCode();
    }
    if (getColresCount() > 0) {
      hash = (37 * hash) + COLRES_FIELD_NUMBER;
      hash = (53 * hash) + getColresList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kr.wise.advisor.prepare.outlier.grpc.OdResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kr.wise.advisor.prepare.outlier.grpc.OdResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kr.wise.advisor.prepare.outlier.OdResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kr.wise.advisor.prepare.outlier.OdResponse)
      kr.wise.advisor.prepare.outlier.grpc.OdResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_OdResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_OdResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kr.wise.advisor.prepare.outlier.grpc.OdResponse.class, kr.wise.advisor.prepare.outlier.grpc.OdResponse.Builder.class);
    }

    // Construct using kr.wise.advisor.prepare.outlier.grpc.OdResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getColresFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      error_ = 0;

      results_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      if (colresBuilder_ == null) {
        colres_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        colresBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_OdResponse_descriptor;
    }

    public kr.wise.advisor.prepare.outlier.grpc.OdResponse getDefaultInstanceForType() {
      return kr.wise.advisor.prepare.outlier.grpc.OdResponse.getDefaultInstance();
    }

    public kr.wise.advisor.prepare.outlier.grpc.OdResponse build() {
      kr.wise.advisor.prepare.outlier.grpc.OdResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kr.wise.advisor.prepare.outlier.grpc.OdResponse buildPartial() {
      kr.wise.advisor.prepare.outlier.grpc.OdResponse result = new kr.wise.advisor.prepare.outlier.grpc.OdResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.error_ = error_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        results_ = java.util.Collections.unmodifiableList(results_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.results_ = results_;
      if (colresBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          colres_ = java.util.Collections.unmodifiableList(colres_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.colres_ = colres_;
      } else {
        result.colres_ = colresBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kr.wise.advisor.prepare.outlier.grpc.OdResponse) {
        return mergeFrom((kr.wise.advisor.prepare.outlier.grpc.OdResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kr.wise.advisor.prepare.outlier.grpc.OdResponse other) {
      if (other == kr.wise.advisor.prepare.outlier.grpc.OdResponse.getDefaultInstance()) return this;
      if (other.getError() != 0) {
        setError(other.getError());
      }
      if (!other.results_.isEmpty()) {
        if (results_.isEmpty()) {
          results_ = other.results_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureResultsIsMutable();
          results_.addAll(other.results_);
        }
        onChanged();
      }
      if (colresBuilder_ == null) {
        if (!other.colres_.isEmpty()) {
          if (colres_.isEmpty()) {
            colres_ = other.colres_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureColresIsMutable();
            colres_.addAll(other.colres_);
          }
          onChanged();
        }
      } else {
        if (!other.colres_.isEmpty()) {
          if (colresBuilder_.isEmpty()) {
            colresBuilder_.dispose();
            colresBuilder_ = null;
            colres_ = other.colres_;
            bitField0_ = (bitField0_ & ~0x00000004);
            colresBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getColresFieldBuilder() : null;
          } else {
            colresBuilder_.addAllMessages(other.colres_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kr.wise.advisor.prepare.outlier.grpc.OdResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kr.wise.advisor.prepare.outlier.grpc.OdResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int error_ ;
    /**
     * <pre>
     * -1 for no error, 0 for bad request, 1 for process error
     * </pre>
     *
     * <code>int32 error = 1;</code>
     */
    public int getError() {
      return error_;
    }
    /**
     * <pre>
     * -1 for no error, 0 for bad request, 1 for process error
     * </pre>
     *
     * <code>int32 error = 1;</code>
     */
    public Builder setError(int value) {
      
      error_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * -1 for no error, 0 for bad request, 1 for process error
     * </pre>
     *
     * <code>int32 error = 1;</code>
     */
    public Builder clearError() {
      
      error_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Boolean> results_ = java.util.Collections.emptyList();
    private void ensureResultsIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        results_ = new java.util.ArrayList<java.lang.Boolean>(results_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated bool results = 2;</code>
     */
    public java.util.List<java.lang.Boolean>
        getResultsList() {
      return java.util.Collections.unmodifiableList(results_);
    }
    /**
     * <code>repeated bool results = 2;</code>
     */
    public int getResultsCount() {
      return results_.size();
    }
    /**
     * <code>repeated bool results = 2;</code>
     */
    public boolean getResults(int index) {
      return results_.get(index);
    }
    /**
     * <code>repeated bool results = 2;</code>
     */
    public Builder setResults(
        int index, boolean value) {
      ensureResultsIsMutable();
      results_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool results = 2;</code>
     */
    public Builder addResults(boolean value) {
      ensureResultsIsMutable();
      results_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool results = 2;</code>
     */
    public Builder addAllResults(
        java.lang.Iterable<? extends java.lang.Boolean> values) {
      ensureResultsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, results_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated bool results = 2;</code>
     */
    public Builder clearResults() {
      results_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private java.util.List<kr.wise.advisor.prepare.outlier.grpc.ColResponse> colres_ =
      java.util.Collections.emptyList();
    private void ensureColresIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        colres_ = new java.util.ArrayList<kr.wise.advisor.prepare.outlier.grpc.ColResponse>(colres_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        kr.wise.advisor.prepare.outlier.grpc.ColResponse, kr.wise.advisor.prepare.outlier.grpc.ColResponse.Builder, kr.wise.advisor.prepare.outlier.grpc.ColResponseOrBuilder> colresBuilder_;

    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public java.util.List<kr.wise.advisor.prepare.outlier.grpc.ColResponse> getColresList() {
      if (colresBuilder_ == null) {
        return java.util.Collections.unmodifiableList(colres_);
      } else {
        return colresBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public int getColresCount() {
      if (colresBuilder_ == null) {
        return colres_.size();
      } else {
        return colresBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public kr.wise.advisor.prepare.outlier.grpc.ColResponse getColres(int index) {
      if (colresBuilder_ == null) {
        return colres_.get(index);
      } else {
        return colresBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public Builder setColres(
        int index, kr.wise.advisor.prepare.outlier.grpc.ColResponse value) {
      if (colresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColresIsMutable();
        colres_.set(index, value);
        onChanged();
      } else {
        colresBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public Builder setColres(
        int index, kr.wise.advisor.prepare.outlier.grpc.ColResponse.Builder builderForValue) {
      if (colresBuilder_ == null) {
        ensureColresIsMutable();
        colres_.set(index, builderForValue.build());
        onChanged();
      } else {
        colresBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public Builder addColres(kr.wise.advisor.prepare.outlier.grpc.ColResponse value) {
      if (colresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColresIsMutable();
        colres_.add(value);
        onChanged();
      } else {
        colresBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public Builder addColres(
        int index, kr.wise.advisor.prepare.outlier.grpc.ColResponse value) {
      if (colresBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColresIsMutable();
        colres_.add(index, value);
        onChanged();
      } else {
        colresBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public Builder addColres(
        kr.wise.advisor.prepare.outlier.grpc.ColResponse.Builder builderForValue) {
      if (colresBuilder_ == null) {
        ensureColresIsMutable();
        colres_.add(builderForValue.build());
        onChanged();
      } else {
        colresBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public Builder addColres(
        int index, kr.wise.advisor.prepare.outlier.grpc.ColResponse.Builder builderForValue) {
      if (colresBuilder_ == null) {
        ensureColresIsMutable();
        colres_.add(index, builderForValue.build());
        onChanged();
      } else {
        colresBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public Builder addAllColres(
        java.lang.Iterable<? extends kr.wise.advisor.prepare.outlier.grpc.ColResponse> values) {
      if (colresBuilder_ == null) {
        ensureColresIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, colres_);
        onChanged();
      } else {
        colresBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public Builder clearColres() {
      if (colresBuilder_ == null) {
        colres_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        colresBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public Builder removeColres(int index) {
      if (colresBuilder_ == null) {
        ensureColresIsMutable();
        colres_.remove(index);
        onChanged();
      } else {
        colresBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public kr.wise.advisor.prepare.outlier.grpc.ColResponse.Builder getColresBuilder(
        int index) {
      return getColresFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public kr.wise.advisor.prepare.outlier.grpc.ColResponseOrBuilder getColresOrBuilder(
        int index) {
      if (colresBuilder_ == null) {
        return colres_.get(index);  } else {
        return colresBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public java.util.List<? extends kr.wise.advisor.prepare.outlier.grpc.ColResponseOrBuilder> 
         getColresOrBuilderList() {
      if (colresBuilder_ != null) {
        return colresBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(colres_);
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public kr.wise.advisor.prepare.outlier.grpc.ColResponse.Builder addColresBuilder() {
      return getColresFieldBuilder().addBuilder(
          kr.wise.advisor.prepare.outlier.grpc.ColResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public kr.wise.advisor.prepare.outlier.grpc.ColResponse.Builder addColresBuilder(
        int index) {
      return getColresFieldBuilder().addBuilder(
          index, kr.wise.advisor.prepare.outlier.grpc.ColResponse.getDefaultInstance());
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
     */
    public java.util.List<kr.wise.advisor.prepare.outlier.grpc.ColResponse.Builder> 
         getColresBuilderList() {
      return getColresFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        kr.wise.advisor.prepare.outlier.grpc.ColResponse, kr.wise.advisor.prepare.outlier.grpc.ColResponse.Builder, kr.wise.advisor.prepare.outlier.grpc.ColResponseOrBuilder> 
        getColresFieldBuilder() {
      if (colresBuilder_ == null) {
        colresBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            kr.wise.advisor.prepare.outlier.grpc.ColResponse, kr.wise.advisor.prepare.outlier.grpc.ColResponse.Builder, kr.wise.advisor.prepare.outlier.grpc.ColResponseOrBuilder>(
                colres_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        colres_ = null;
      }
      return colresBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:kr.wise.advisor.prepare.outlier.OdResponse)
  }

  // @@protoc_insertion_point(class_scope:kr.wise.advisor.prepare.outlier.OdResponse)
  private static final kr.wise.advisor.prepare.outlier.grpc.OdResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kr.wise.advisor.prepare.outlier.grpc.OdResponse();
  }

  public static kr.wise.advisor.prepare.outlier.grpc.OdResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OdResponse>
      PARSER = new com.google.protobuf.AbstractParser<OdResponse>() {
    public OdResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new OdResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OdResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OdResponse> getParserForType() {
    return PARSER;
  }

  public kr.wise.advisor.prepare.outlier.grpc.OdResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

