// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: odservice.proto

package kr.wise.advisor.prepare.outlier.grpc;

/**
 * Protobuf type {@code kr.wise.advisor.prepare.outlier.OdRequest}
 */
public  final class OdRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kr.wise.advisor.prepare.outlier.OdRequest)
    OdRequestOrBuilder {
  // Use OdRequest.newBuilder() to construct.
  private OdRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OdRequest() {
    tableName_ = "";
    attributes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    varId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    num_ = 0;
    contamination_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private OdRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            tableName_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              attributes_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000002;
            }
            attributes_.add(s);
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              varId_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000004;
            }
            varId_.add(s);
            break;
          }
          case 32: {

            num_ = input.readUInt32();
            break;
          }
          case 45: {

            contamination_ = input.readFloat();
            break;
          }
          case 50: {
            kr.wise.advisor.prepare.summary.grpc.TargetDbms.Builder subBuilder = null;
            if (tgtDbms_ != null) {
              subBuilder = tgtDbms_.toBuilder();
            }
            tgtDbms_ = input.readMessage(kr.wise.advisor.prepare.summary.grpc.TargetDbms.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(tgtDbms_);
              tgtDbms_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        attributes_ = attributes_.getUnmodifiableView();
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        varId_ = varId_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_OdRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_OdRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kr.wise.advisor.prepare.outlier.grpc.OdRequest.class, kr.wise.advisor.prepare.outlier.grpc.OdRequest.Builder.class);
  }

  private int bitField0_;
  public static final int TABLENAME_FIELD_NUMBER = 1;
  private volatile java.lang.Object tableName_;
  /**
   * <code>string tableName = 1;</code>
   */
  public java.lang.String getTableName() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      tableName_ = s;
      return s;
    }
  }
  /**
   * <code>string tableName = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTableNameBytes() {
    java.lang.Object ref = tableName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      tableName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ATTRIBUTES_FIELD_NUMBER = 2;
  private com.google.protobuf.LazyStringList attributes_;
  /**
   * <code>repeated string attributes = 2;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getAttributesList() {
    return attributes_;
  }
  /**
   * <code>repeated string attributes = 2;</code>
   */
  public int getAttributesCount() {
    return attributes_.size();
  }
  /**
   * <code>repeated string attributes = 2;</code>
   */
  public java.lang.String getAttributes(int index) {
    return attributes_.get(index);
  }
  /**
   * <code>repeated string attributes = 2;</code>
   */
  public com.google.protobuf.ByteString
      getAttributesBytes(int index) {
    return attributes_.getByteString(index);
  }

  public static final int VARID_FIELD_NUMBER = 3;
  private com.google.protobuf.LazyStringList varId_;
  /**
   * <code>repeated string varId = 3;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getVarIdList() {
    return varId_;
  }
  /**
   * <code>repeated string varId = 3;</code>
   */
  public int getVarIdCount() {
    return varId_.size();
  }
  /**
   * <code>repeated string varId = 3;</code>
   */
  public java.lang.String getVarId(int index) {
    return varId_.get(index);
  }
  /**
   * <code>repeated string varId = 3;</code>
   */
  public com.google.protobuf.ByteString
      getVarIdBytes(int index) {
    return varId_.getByteString(index);
  }

  public static final int NUM_FIELD_NUMBER = 4;
  private int num_;
  /**
   * <pre>
   * number of neighborhoods only for LOF
   * </pre>
   *
   * <code>uint32 num = 4;</code>
   */
  public int getNum() {
    return num_;
  }

  public static final int CONTAMINATION_FIELD_NUMBER = 5;
  private float contamination_;
  /**
   * <pre>
   * value between 0 and 0.3
   * </pre>
   *
   * <code>float contamination = 5;</code>
   */
  public float getContamination() {
    return contamination_;
  }

  public static final int TGTDBMS_FIELD_NUMBER = 6;
  private kr.wise.advisor.prepare.summary.grpc.TargetDbms tgtDbms_;
  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 6;</code>
   */
  public boolean hasTgtDbms() {
    return tgtDbms_ != null;
  }
  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 6;</code>
   */
  public kr.wise.advisor.prepare.summary.grpc.TargetDbms getTgtDbms() {
    return tgtDbms_ == null ? kr.wise.advisor.prepare.summary.grpc.TargetDbms.getDefaultInstance() : tgtDbms_;
  }
  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 6;</code>
   */
  public kr.wise.advisor.prepare.summary.grpc.TargetDbmsOrBuilder getTgtDbmsOrBuilder() {
    return getTgtDbms();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTableNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tableName_);
    }
    for (int i = 0; i < attributes_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, attributes_.getRaw(i));
    }
    for (int i = 0; i < varId_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, varId_.getRaw(i));
    }
    if (num_ != 0) {
      output.writeUInt32(4, num_);
    }
    if (contamination_ != 0F) {
      output.writeFloat(5, contamination_);
    }
    if (tgtDbms_ != null) {
      output.writeMessage(6, getTgtDbms());
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTableNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tableName_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < attributes_.size(); i++) {
        dataSize += computeStringSizeNoTag(attributes_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAttributesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < varId_.size(); i++) {
        dataSize += computeStringSizeNoTag(varId_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getVarIdList().size();
    }
    if (num_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, num_);
    }
    if (contamination_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(5, contamination_);
    }
    if (tgtDbms_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getTgtDbms());
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kr.wise.advisor.prepare.outlier.grpc.OdRequest)) {
      return super.equals(obj);
    }
    kr.wise.advisor.prepare.outlier.grpc.OdRequest other = (kr.wise.advisor.prepare.outlier.grpc.OdRequest) obj;

    boolean result = true;
    result = result && getTableName()
        .equals(other.getTableName());
    result = result && getAttributesList()
        .equals(other.getAttributesList());
    result = result && getVarIdList()
        .equals(other.getVarIdList());
    result = result && (getNum()
        == other.getNum());
    result = result && (
        java.lang.Float.floatToIntBits(getContamination())
        == java.lang.Float.floatToIntBits(
            other.getContamination()));
    result = result && (hasTgtDbms() == other.hasTgtDbms());
    if (hasTgtDbms()) {
      result = result && getTgtDbms()
          .equals(other.getTgtDbms());
    }
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TABLENAME_FIELD_NUMBER;
    hash = (53 * hash) + getTableName().hashCode();
    if (getAttributesCount() > 0) {
      hash = (37 * hash) + ATTRIBUTES_FIELD_NUMBER;
      hash = (53 * hash) + getAttributesList().hashCode();
    }
    if (getVarIdCount() > 0) {
      hash = (37 * hash) + VARID_FIELD_NUMBER;
      hash = (53 * hash) + getVarIdList().hashCode();
    }
    hash = (37 * hash) + NUM_FIELD_NUMBER;
    hash = (53 * hash) + getNum();
    hash = (37 * hash) + CONTAMINATION_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getContamination());
    if (hasTgtDbms()) {
      hash = (37 * hash) + TGTDBMS_FIELD_NUMBER;
      hash = (53 * hash) + getTgtDbms().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kr.wise.advisor.prepare.outlier.grpc.OdRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.outlier.grpc.OdRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kr.wise.advisor.prepare.outlier.grpc.OdRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kr.wise.advisor.prepare.outlier.OdRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kr.wise.advisor.prepare.outlier.OdRequest)
      kr.wise.advisor.prepare.outlier.grpc.OdRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_OdRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_OdRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kr.wise.advisor.prepare.outlier.grpc.OdRequest.class, kr.wise.advisor.prepare.outlier.grpc.OdRequest.Builder.class);
    }

    // Construct using kr.wise.advisor.prepare.outlier.grpc.OdRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      tableName_ = "";

      attributes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      varId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      num_ = 0;

      contamination_ = 0F;

      if (tgtDbmsBuilder_ == null) {
        tgtDbms_ = null;
      } else {
        tgtDbms_ = null;
        tgtDbmsBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kr.wise.advisor.prepare.outlier.grpc.OutlierProcess.internal_static_kr_wise_advisor_prepare_outlier_OdRequest_descriptor;
    }

    public kr.wise.advisor.prepare.outlier.grpc.OdRequest getDefaultInstanceForType() {
      return kr.wise.advisor.prepare.outlier.grpc.OdRequest.getDefaultInstance();
    }

    public kr.wise.advisor.prepare.outlier.grpc.OdRequest build() {
      kr.wise.advisor.prepare.outlier.grpc.OdRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kr.wise.advisor.prepare.outlier.grpc.OdRequest buildPartial() {
      kr.wise.advisor.prepare.outlier.grpc.OdRequest result = new kr.wise.advisor.prepare.outlier.grpc.OdRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.tableName_ = tableName_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        attributes_ = attributes_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.attributes_ = attributes_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        varId_ = varId_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.varId_ = varId_;
      result.num_ = num_;
      result.contamination_ = contamination_;
      if (tgtDbmsBuilder_ == null) {
        result.tgtDbms_ = tgtDbms_;
      } else {
        result.tgtDbms_ = tgtDbmsBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kr.wise.advisor.prepare.outlier.grpc.OdRequest) {
        return mergeFrom((kr.wise.advisor.prepare.outlier.grpc.OdRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kr.wise.advisor.prepare.outlier.grpc.OdRequest other) {
      if (other == kr.wise.advisor.prepare.outlier.grpc.OdRequest.getDefaultInstance()) return this;
      if (!other.getTableName().isEmpty()) {
        tableName_ = other.tableName_;
        onChanged();
      }
      if (!other.attributes_.isEmpty()) {
        if (attributes_.isEmpty()) {
          attributes_ = other.attributes_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureAttributesIsMutable();
          attributes_.addAll(other.attributes_);
        }
        onChanged();
      }
      if (!other.varId_.isEmpty()) {
        if (varId_.isEmpty()) {
          varId_ = other.varId_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureVarIdIsMutable();
          varId_.addAll(other.varId_);
        }
        onChanged();
      }
      if (other.getNum() != 0) {
        setNum(other.getNum());
      }
      if (other.getContamination() != 0F) {
        setContamination(other.getContamination());
      }
      if (other.hasTgtDbms()) {
        mergeTgtDbms(other.getTgtDbms());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kr.wise.advisor.prepare.outlier.grpc.OdRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kr.wise.advisor.prepare.outlier.grpc.OdRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object tableName_ = "";
    /**
     * <code>string tableName = 1;</code>
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string tableName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string tableName = 1;</code>
     */
    public Builder setTableName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      tableName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string tableName = 1;</code>
     */
    public Builder clearTableName() {
      
      tableName_ = getDefaultInstance().getTableName();
      onChanged();
      return this;
    }
    /**
     * <code>string tableName = 1;</code>
     */
    public Builder setTableNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      tableName_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList attributes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureAttributesIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        attributes_ = new com.google.protobuf.LazyStringArrayList(attributes_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated string attributes = 2;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getAttributesList() {
      return attributes_.getUnmodifiableView();
    }
    /**
     * <code>repeated string attributes = 2;</code>
     */
    public int getAttributesCount() {
      return attributes_.size();
    }
    /**
     * <code>repeated string attributes = 2;</code>
     */
    public java.lang.String getAttributes(int index) {
      return attributes_.get(index);
    }
    /**
     * <code>repeated string attributes = 2;</code>
     */
    public com.google.protobuf.ByteString
        getAttributesBytes(int index) {
      return attributes_.getByteString(index);
    }
    /**
     * <code>repeated string attributes = 2;</code>
     */
    public Builder setAttributes(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAttributesIsMutable();
      attributes_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string attributes = 2;</code>
     */
    public Builder addAttributes(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureAttributesIsMutable();
      attributes_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string attributes = 2;</code>
     */
    public Builder addAllAttributes(
        java.lang.Iterable<java.lang.String> values) {
      ensureAttributesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, attributes_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string attributes = 2;</code>
     */
    public Builder clearAttributes() {
      attributes_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string attributes = 2;</code>
     */
    public Builder addAttributesBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureAttributesIsMutable();
      attributes_.add(value);
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringList varId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureVarIdIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        varId_ = new com.google.protobuf.LazyStringArrayList(varId_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <code>repeated string varId = 3;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getVarIdList() {
      return varId_.getUnmodifiableView();
    }
    /**
     * <code>repeated string varId = 3;</code>
     */
    public int getVarIdCount() {
      return varId_.size();
    }
    /**
     * <code>repeated string varId = 3;</code>
     */
    public java.lang.String getVarId(int index) {
      return varId_.get(index);
    }
    /**
     * <code>repeated string varId = 3;</code>
     */
    public com.google.protobuf.ByteString
        getVarIdBytes(int index) {
      return varId_.getByteString(index);
    }
    /**
     * <code>repeated string varId = 3;</code>
     */
    public Builder setVarId(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureVarIdIsMutable();
      varId_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string varId = 3;</code>
     */
    public Builder addVarId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureVarIdIsMutable();
      varId_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string varId = 3;</code>
     */
    public Builder addAllVarId(
        java.lang.Iterable<java.lang.String> values) {
      ensureVarIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, varId_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string varId = 3;</code>
     */
    public Builder clearVarId() {
      varId_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string varId = 3;</code>
     */
    public Builder addVarIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureVarIdIsMutable();
      varId_.add(value);
      onChanged();
      return this;
    }

    private int num_ ;
    /**
     * <pre>
     * number of neighborhoods only for LOF
     * </pre>
     *
     * <code>uint32 num = 4;</code>
     */
    public int getNum() {
      return num_;
    }
    /**
     * <pre>
     * number of neighborhoods only for LOF
     * </pre>
     *
     * <code>uint32 num = 4;</code>
     */
    public Builder setNum(int value) {
      
      num_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * number of neighborhoods only for LOF
     * </pre>
     *
     * <code>uint32 num = 4;</code>
     */
    public Builder clearNum() {
      
      num_ = 0;
      onChanged();
      return this;
    }

    private float contamination_ ;
    /**
     * <pre>
     * value between 0 and 0.3
     * </pre>
     *
     * <code>float contamination = 5;</code>
     */
    public float getContamination() {
      return contamination_;
    }
    /**
     * <pre>
     * value between 0 and 0.3
     * </pre>
     *
     * <code>float contamination = 5;</code>
     */
    public Builder setContamination(float value) {
      
      contamination_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * value between 0 and 0.3
     * </pre>
     *
     * <code>float contamination = 5;</code>
     */
    public Builder clearContamination() {
      
      contamination_ = 0F;
      onChanged();
      return this;
    }

    private kr.wise.advisor.prepare.summary.grpc.TargetDbms tgtDbms_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        kr.wise.advisor.prepare.summary.grpc.TargetDbms, kr.wise.advisor.prepare.summary.grpc.TargetDbms.Builder, kr.wise.advisor.prepare.summary.grpc.TargetDbmsOrBuilder> tgtDbmsBuilder_;
    /**
     * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 6;</code>
     */
    public boolean hasTgtDbms() {
      return tgtDbmsBuilder_ != null || tgtDbms_ != null;
    }
    /**
     * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 6;</code>
     */
    public kr.wise.advisor.prepare.summary.grpc.TargetDbms getTgtDbms() {
      if (tgtDbmsBuilder_ == null) {
        return tgtDbms_ == null ? kr.wise.advisor.prepare.summary.grpc.TargetDbms.getDefaultInstance() : tgtDbms_;
      } else {
        return tgtDbmsBuilder_.getMessage();
      }
    }
    /**
     * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 6;</code>
     */
    public Builder setTgtDbms(kr.wise.advisor.prepare.summary.grpc.TargetDbms value) {
      if (tgtDbmsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tgtDbms_ = value;
        onChanged();
      } else {
        tgtDbmsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 6;</code>
     */
    public Builder setTgtDbms(
        kr.wise.advisor.prepare.summary.grpc.TargetDbms.Builder builderForValue) {
      if (tgtDbmsBuilder_ == null) {
        tgtDbms_ = builderForValue.build();
        onChanged();
      } else {
        tgtDbmsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 6;</code>
     */
    public Builder mergeTgtDbms(kr.wise.advisor.prepare.summary.grpc.TargetDbms value) {
      if (tgtDbmsBuilder_ == null) {
        if (tgtDbms_ != null) {
          tgtDbms_ =
            kr.wise.advisor.prepare.summary.grpc.TargetDbms.newBuilder(tgtDbms_).mergeFrom(value).buildPartial();
        } else {
          tgtDbms_ = value;
        }
        onChanged();
      } else {
        tgtDbmsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 6;</code>
     */
    public Builder clearTgtDbms() {
      if (tgtDbmsBuilder_ == null) {
        tgtDbms_ = null;
        onChanged();
      } else {
        tgtDbms_ = null;
        tgtDbmsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 6;</code>
     */
    public kr.wise.advisor.prepare.summary.grpc.TargetDbms.Builder getTgtDbmsBuilder() {
      
      onChanged();
      return getTgtDbmsFieldBuilder().getBuilder();
    }
    /**
     * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 6;</code>
     */
    public kr.wise.advisor.prepare.summary.grpc.TargetDbmsOrBuilder getTgtDbmsOrBuilder() {
      if (tgtDbmsBuilder_ != null) {
        return tgtDbmsBuilder_.getMessageOrBuilder();
      } else {
        return tgtDbms_ == null ?
            kr.wise.advisor.prepare.summary.grpc.TargetDbms.getDefaultInstance() : tgtDbms_;
      }
    }
    /**
     * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        kr.wise.advisor.prepare.summary.grpc.TargetDbms, kr.wise.advisor.prepare.summary.grpc.TargetDbms.Builder, kr.wise.advisor.prepare.summary.grpc.TargetDbmsOrBuilder> 
        getTgtDbmsFieldBuilder() {
      if (tgtDbmsBuilder_ == null) {
        tgtDbmsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            kr.wise.advisor.prepare.summary.grpc.TargetDbms, kr.wise.advisor.prepare.summary.grpc.TargetDbms.Builder, kr.wise.advisor.prepare.summary.grpc.TargetDbmsOrBuilder>(
                getTgtDbms(),
                getParentForChildren(),
                isClean());
        tgtDbms_ = null;
      }
      return tgtDbmsBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:kr.wise.advisor.prepare.outlier.OdRequest)
  }

  // @@protoc_insertion_point(class_scope:kr.wise.advisor.prepare.outlier.OdRequest)
  private static final kr.wise.advisor.prepare.outlier.grpc.OdRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kr.wise.advisor.prepare.outlier.grpc.OdRequest();
  }

  public static kr.wise.advisor.prepare.outlier.grpc.OdRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OdRequest>
      PARSER = new com.google.protobuf.AbstractParser<OdRequest>() {
    public OdRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new OdRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OdRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OdRequest> getParserForType() {
    return PARSER;
  }

  public kr.wise.advisor.prepare.outlier.grpc.OdRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

