// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: odservice.proto

package kr.wise.advisor.prepare.outlier.grpc;

public interface OdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kr.wise.advisor.prepare.outlier.OdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * -1 for no error, 0 for bad request, 1 for process error
   * </pre>
   *
   * <code>int32 error = 1;</code>
   */
  int getError();

  /**
   * <code>repeated bool results = 2;</code>
   */
  java.util.List<java.lang.Boolean> getResultsList();
  /**
   * <code>repeated bool results = 2;</code>
   */
  int getResultsCount();
  /**
   * <code>repeated bool results = 2;</code>
   */
  boolean getResults(int index);

  /**
   * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
   */
  java.util.List<kr.wise.advisor.prepare.outlier.grpc.ColResponse> 
      getColresList();
  /**
   * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
   */
  kr.wise.advisor.prepare.outlier.grpc.ColResponse getColres(int index);
  /**
   * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
   */
  int getColresCount();
  /**
   * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
   */
  java.util.List<? extends kr.wise.advisor.prepare.outlier.grpc.ColResponseOrBuilder> 
      getColresOrBuilderList();
  /**
   * <code>repeated .kr.wise.advisor.prepare.outlier.ColResponse colres = 3;</code>
   */
  kr.wise.advisor.prepare.outlier.grpc.ColResponseOrBuilder getColresOrBuilder(
      int index);
}
