// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: odservice.proto

package kr.wise.advisor.prepare.outlier.grpc;

public final class OutlierProcess {
  private OutlierProcess() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kr_wise_advisor_prepare_outlier_OdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kr_wise_advisor_prepare_outlier_OdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kr_wise_advisor_prepare_outlier_OdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kr_wise_advisor_prepare_outlier_OdResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kr_wise_advisor_prepare_outlier_ColResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kr_wise_advisor_prepare_outlier_ColResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017odservice.proto\022\037kr.wise.advisor.prepa" +
      "re.outlier\032\rsummary.proto\"\243\001\n\tOdRequest\022" +
      "\021\n\ttableName\030\001 \001(\t\022\022\n\nattributes\030\002 \003(\t\022\r" +
      "\n\005varId\030\003 \003(\t\022\013\n\003num\030\004 \001(\r\022\025\n\rcontaminat" +
      "ion\030\005 \001(\002\022<\n\007tgtDbms\030\006 \001(\0132+.kr.wise.adv" +
      "isor.prepare.summary.TargetDbms\"j\n\nOdRes" +
      "ponse\022\r\n\005error\030\001 \001(\005\022\017\n\007results\030\002 \003(\010\022<\n" +
      "\006colres\030\003 \003(\0132,.kr.wise.advisor.prepare." +
      "outlier.ColResponse\"<\n\013ColResponse\022\016\n\006ar" +
      "rtnm\030\001 \001(\t\022\r\n\005varId\030\002 \001(\t\022\016\n\006colval\030\003 \003(",
      "\0022\227\003\n\tOdService\022`\n\003lof\022*.kr.wise.advisor" +
      ".prepare.outlier.OdRequest\032+.kr.wise.adv" +
      "isor.prepare.outlier.OdResponse\"\000\022b\n\005ocs" +
      "vm\022*.kr.wise.advisor.prepare.outlier.OdR" +
      "equest\032+.kr.wise.advisor.prepare.outlier" +
      ".OdResponse\"\000\022_\n\002ee\022*.kr.wise.advisor.pr" +
      "epare.outlier.OdRequest\032+.kr.wise.adviso" +
      "r.prepare.outlier.OdResponse\"\000\022c\n\006isofor" +
      "\022*.kr.wise.advisor.prepare.outlier.OdReq" +
      "uest\032+.kr.wise.advisor.prepare.outlier.O",
      "dResponse\"\000B8\n$kr.wise.advisor.prepare.o" +
      "utlier.grpcB\016OutlierProcessP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          kr.wise.advisor.prepare.summary.grpc.SummaryProcess.getDescriptor(),
        }, assigner);
    internal_static_kr_wise_advisor_prepare_outlier_OdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kr_wise_advisor_prepare_outlier_OdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kr_wise_advisor_prepare_outlier_OdRequest_descriptor,
        new java.lang.String[] { "TableName", "Attributes", "VarId", "Num", "Contamination", "TgtDbms", });
    internal_static_kr_wise_advisor_prepare_outlier_OdResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kr_wise_advisor_prepare_outlier_OdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kr_wise_advisor_prepare_outlier_OdResponse_descriptor,
        new java.lang.String[] { "Error", "Results", "Colres", });
    internal_static_kr_wise_advisor_prepare_outlier_ColResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_kr_wise_advisor_prepare_outlier_ColResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kr_wise_advisor_prepare_outlier_ColResponse_descriptor,
        new java.lang.String[] { "Arrtnm", "VarId", "Colval", });
    kr.wise.advisor.prepare.summary.grpc.SummaryProcess.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
