// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dmnpredict.proto

package kr.wise.advisor.prepare.domain.grpc;

/**
 * Protobuf type {@code domain.DmnPredictResult}
 */
public  final class DmnPredictResult extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:domain.DmnPredictResult)
    DmnPredictResultOrBuilder {
  // Use DmnPredictResult.newBuilder() to construct.
  private DmnPredictResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DmnPredictResult() {
    anlVarId_ = "";
    dmnPrb_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private DmnPredictResult(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            anlVarId_ = s;
            break;
          }
          case 21: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              dmnPrb_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000002;
            }
            dmnPrb_.add(input.readFloat());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
              dmnPrb_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              dmnPrb_.add(input.readFloat());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        dmnPrb_ = java.util.Collections.unmodifiableList(dmnPrb_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_DmnPredictResult_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_DmnPredictResult_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.class, kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.Builder.class);
  }

  private int bitField0_;
  public static final int ANLVARID_FIELD_NUMBER = 1;
  private volatile java.lang.Object anlVarId_;
  /**
   * <code>string anlVarId = 1;</code>
   */
  public java.lang.String getAnlVarId() {
    java.lang.Object ref = anlVarId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      anlVarId_ = s;
      return s;
    }
  }
  /**
   * <code>string anlVarId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getAnlVarIdBytes() {
    java.lang.Object ref = anlVarId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      anlVarId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DMNPRB_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Float> dmnPrb_;
  /**
   * <code>repeated float dmnPrb = 2;</code>
   */
  public java.util.List<java.lang.Float>
      getDmnPrbList() {
    return dmnPrb_;
  }
  /**
   * <code>repeated float dmnPrb = 2;</code>
   */
  public int getDmnPrbCount() {
    return dmnPrb_.size();
  }
  /**
   * <code>repeated float dmnPrb = 2;</code>
   */
  public float getDmnPrb(int index) {
    return dmnPrb_.get(index);
  }
  private int dmnPrbMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getAnlVarIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, anlVarId_);
    }
    if (getDmnPrbList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(dmnPrbMemoizedSerializedSize);
    }
    for (int i = 0; i < dmnPrb_.size(); i++) {
      output.writeFloatNoTag(dmnPrb_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getAnlVarIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, anlVarId_);
    }
    {
      int dataSize = 0;
      dataSize = 4 * getDmnPrbList().size();
      size += dataSize;
      if (!getDmnPrbList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      dmnPrbMemoizedSerializedSize = dataSize;
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kr.wise.advisor.prepare.domain.grpc.DmnPredictResult)) {
      return super.equals(obj);
    }
    kr.wise.advisor.prepare.domain.grpc.DmnPredictResult other = (kr.wise.advisor.prepare.domain.grpc.DmnPredictResult) obj;

    boolean result = true;
    result = result && getAnlVarId()
        .equals(other.getAnlVarId());
    result = result && getDmnPrbList()
        .equals(other.getDmnPrbList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ANLVARID_FIELD_NUMBER;
    hash = (53 * hash) + getAnlVarId().hashCode();
    if (getDmnPrbCount() > 0) {
      hash = (37 * hash) + DMNPRB_FIELD_NUMBER;
      hash = (53 * hash) + getDmnPrbList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kr.wise.advisor.prepare.domain.grpc.DmnPredictResult parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnPredictResult parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnPredictResult parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnPredictResult parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnPredictResult parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnPredictResult parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnPredictResult parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnPredictResult parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnPredictResult parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnPredictResult parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnPredictResult parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnPredictResult parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kr.wise.advisor.prepare.domain.grpc.DmnPredictResult prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code domain.DmnPredictResult}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:domain.DmnPredictResult)
      kr.wise.advisor.prepare.domain.grpc.DmnPredictResultOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_DmnPredictResult_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_DmnPredictResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.class, kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.Builder.class);
    }

    // Construct using kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      anlVarId_ = "";

      dmnPrb_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_DmnPredictResult_descriptor;
    }

    public kr.wise.advisor.prepare.domain.grpc.DmnPredictResult getDefaultInstanceForType() {
      return kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.getDefaultInstance();
    }

    public kr.wise.advisor.prepare.domain.grpc.DmnPredictResult build() {
      kr.wise.advisor.prepare.domain.grpc.DmnPredictResult result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kr.wise.advisor.prepare.domain.grpc.DmnPredictResult buildPartial() {
      kr.wise.advisor.prepare.domain.grpc.DmnPredictResult result = new kr.wise.advisor.prepare.domain.grpc.DmnPredictResult(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.anlVarId_ = anlVarId_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        dmnPrb_ = java.util.Collections.unmodifiableList(dmnPrb_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.dmnPrb_ = dmnPrb_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kr.wise.advisor.prepare.domain.grpc.DmnPredictResult) {
        return mergeFrom((kr.wise.advisor.prepare.domain.grpc.DmnPredictResult)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kr.wise.advisor.prepare.domain.grpc.DmnPredictResult other) {
      if (other == kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.getDefaultInstance()) return this;
      if (!other.getAnlVarId().isEmpty()) {
        anlVarId_ = other.anlVarId_;
        onChanged();
      }
      if (!other.dmnPrb_.isEmpty()) {
        if (dmnPrb_.isEmpty()) {
          dmnPrb_ = other.dmnPrb_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureDmnPrbIsMutable();
          dmnPrb_.addAll(other.dmnPrb_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kr.wise.advisor.prepare.domain.grpc.DmnPredictResult parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kr.wise.advisor.prepare.domain.grpc.DmnPredictResult) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object anlVarId_ = "";
    /**
     * <code>string anlVarId = 1;</code>
     */
    public java.lang.String getAnlVarId() {
      java.lang.Object ref = anlVarId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        anlVarId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string anlVarId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getAnlVarIdBytes() {
      java.lang.Object ref = anlVarId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        anlVarId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string anlVarId = 1;</code>
     */
    public Builder setAnlVarId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      anlVarId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string anlVarId = 1;</code>
     */
    public Builder clearAnlVarId() {
      
      anlVarId_ = getDefaultInstance().getAnlVarId();
      onChanged();
      return this;
    }
    /**
     * <code>string anlVarId = 1;</code>
     */
    public Builder setAnlVarIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      anlVarId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Float> dmnPrb_ = java.util.Collections.emptyList();
    private void ensureDmnPrbIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        dmnPrb_ = new java.util.ArrayList<java.lang.Float>(dmnPrb_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <code>repeated float dmnPrb = 2;</code>
     */
    public java.util.List<java.lang.Float>
        getDmnPrbList() {
      return java.util.Collections.unmodifiableList(dmnPrb_);
    }
    /**
     * <code>repeated float dmnPrb = 2;</code>
     */
    public int getDmnPrbCount() {
      return dmnPrb_.size();
    }
    /**
     * <code>repeated float dmnPrb = 2;</code>
     */
    public float getDmnPrb(int index) {
      return dmnPrb_.get(index);
    }
    /**
     * <code>repeated float dmnPrb = 2;</code>
     */
    public Builder setDmnPrb(
        int index, float value) {
      ensureDmnPrbIsMutable();
      dmnPrb_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float dmnPrb = 2;</code>
     */
    public Builder addDmnPrb(float value) {
      ensureDmnPrbIsMutable();
      dmnPrb_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float dmnPrb = 2;</code>
     */
    public Builder addAllDmnPrb(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureDmnPrbIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, dmnPrb_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated float dmnPrb = 2;</code>
     */
    public Builder clearDmnPrb() {
      dmnPrb_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:domain.DmnPredictResult)
  }

  // @@protoc_insertion_point(class_scope:domain.DmnPredictResult)
  private static final kr.wise.advisor.prepare.domain.grpc.DmnPredictResult DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kr.wise.advisor.prepare.domain.grpc.DmnPredictResult();
  }

  public static kr.wise.advisor.prepare.domain.grpc.DmnPredictResult getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DmnPredictResult>
      PARSER = new com.google.protobuf.AbstractParser<DmnPredictResult>() {
    public DmnPredictResult parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DmnPredictResult(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DmnPredictResult> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DmnPredictResult> getParserForType() {
    return PARSER;
  }

  public kr.wise.advisor.prepare.domain.grpc.DmnPredictResult getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

