// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dmnpredict.proto

package kr.wise.advisor.prepare.domain.grpc;

public interface DmnPredictResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domain.DmnPredictResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string anlVarId = 1;</code>
   */
  java.lang.String getAnlVarId();
  /**
   * <code>string anlVarId = 1;</code>
   */
  com.google.protobuf.ByteString
      getAnlVarIdBytes();

  /**
   * <code>repeated float dmnPrb = 2;</code>
   */
  java.util.List<java.lang.Float> getDmnPrbList();
  /**
   * <code>repeated float dmnPrb = 2;</code>
   */
  int getDmnPrbCount();
  /**
   * <code>repeated float dmnPrb = 2;</code>
   */
  float getDmnPrb(int index);
}
