// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dmnpredict.proto

package kr.wise.advisor.prepare.domain.grpc;

public final class DmnPredictProcess {
  private DmnPredictProcess() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domain_DmnRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domain_DmnRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domain_TargetDbms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domain_TargetDbms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domain_DmnResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domain_DmnResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domain_DmnPredictResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_domain_DmnPredictResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020dmnpredict.proto\022\006domain\"A\n\nDmnRequest" +
      "\022\016\n\006rqstNo\030\001 \001(\t\022#\n\007tgtDbms\030\002 \001(\0132\022.doma" +
      "in.TargetDbms\"\232\002\n\nTargetDbms\022\023\n\013dbConnTr" +
      "gId\030\001 \001(\t\022\024\n\014dbConnTrgPnm\030\002 \001(\t\022\024\n\014dbCon" +
      "nTrgLnm\030\003 \001(\t\022\021\n\tdbmsTypCd\030\004 \001(\t\022\022\n\ndbms" +
      "VersCd\030\005 \001(\t\022\030\n\020connTrgDbLnkChrw\030\006 \001(\t\022\025" +
      "\n\rconnTrgLnkUrl\030\007 \001(\t\022\025\n\rconnTrgDrvrNm\030\010" +
      " \001(\t\022\022\n\ndbConnAcId\030\t \001(\t\022\023\n\013dbConnAcPwd\030" +
      "\n \001(\t\022\017\n\007dbSchId\030\013 \001(\t\022\020\n\010dbSchPnm\030\014 \001(\t" +
      "\022\020\n\010dbSchLnm\030\r \001(\t\";\n\013DmnResponse\022,\n\ndmn",
      "pdtlist\030\001 \003(\0132\030.domain.DmnPredictResult\"" +
      "4\n\020DmnPredictResult\022\020\n\010anlVarId\030\001 \001(\t\022\016\n" +
      "\006dmnPrb\030\002 \003(\0022H\n\nDmnPredict\022:\n\rGetDmnPre" +
      "dict\022\022.domain.DmnRequest\032\023.domain.DmnRes" +
      "ponse\"\000B:\n#kr.wise.advisor.prepare.domai" +
      "n.grpcB\021DmnPredictProcessP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_domain_DmnRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_domain_DmnRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domain_DmnRequest_descriptor,
        new java.lang.String[] { "RqstNo", "TgtDbms", });
    internal_static_domain_TargetDbms_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_domain_TargetDbms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domain_TargetDbms_descriptor,
        new java.lang.String[] { "DbConnTrgId", "DbConnTrgPnm", "DbConnTrgLnm", "DbmsTypCd", "DbmsVersCd", "ConnTrgDbLnkChrw", "ConnTrgLnkUrl", "ConnTrgDrvrNm", "DbConnAcId", "DbConnAcPwd", "DbSchId", "DbSchPnm", "DbSchLnm", });
    internal_static_domain_DmnResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_domain_DmnResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domain_DmnResponse_descriptor,
        new java.lang.String[] { "Dmnpdtlist", });
    internal_static_domain_DmnPredictResult_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_domain_DmnPredictResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_domain_DmnPredictResult_descriptor,
        new java.lang.String[] { "AnlVarId", "DmnPrb", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
