// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dmnpredict.proto

package kr.wise.advisor.prepare.domain.grpc;

public interface DmnResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domain.DmnResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
   */
  java.util.List<kr.wise.advisor.prepare.domain.grpc.DmnPredictResult> 
      getDmnpdtlistList();
  /**
   * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
   */
  kr.wise.advisor.prepare.domain.grpc.DmnPredictResult getDmnpdtlist(int index);
  /**
   * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
   */
  int getDmnpdtlistCount();
  /**
   * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
   */
  java.util.List<? extends kr.wise.advisor.prepare.domain.grpc.DmnPredictResultOrBuilder> 
      getDmnpdtlistOrBuilderList();
  /**
   * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
   */
  kr.wise.advisor.prepare.domain.grpc.DmnPredictResultOrBuilder getDmnpdtlistOrBuilder(
      int index);
}
