// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dmnpredict.proto

package kr.wise.advisor.prepare.domain.grpc;

public interface DmnRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:domain.DmnRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string rqstNo = 1;</code>
   */
  java.lang.String getRqstNo();
  /**
   * <code>string rqstNo = 1;</code>
   */
  com.google.protobuf.ByteString
      getRqstNoBytes();

  /**
   * <code>.domain.TargetDbms tgtDbms = 2;</code>
   */
  boolean hasTgtDbms();
  /**
   * <code>.domain.TargetDbms tgtDbms = 2;</code>
   */
  kr.wise.advisor.prepare.domain.grpc.TargetDbms getTgtDbms();
  /**
   * <code>.domain.TargetDbms tgtDbms = 2;</code>
   */
  kr.wise.advisor.prepare.domain.grpc.TargetDbmsOrBuilder getTgtDbmsOrBuilder();
}
