// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dmnpredict.proto

package kr.wise.advisor.prepare.domain.grpc;

/**
 * Protobuf type {@code domain.DmnResponse}
 */
public  final class DmnResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:domain.DmnResponse)
    DmnResponseOrBuilder {
  // Use DmnResponse.newBuilder() to construct.
  private DmnResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DmnResponse() {
    dmnpdtlist_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private DmnResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              dmnpdtlist_ = new java.util.ArrayList<kr.wise.advisor.prepare.domain.grpc.DmnPredictResult>();
              mutable_bitField0_ |= 0x00000001;
            }
            dmnpdtlist_.add(
                input.readMessage(kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        dmnpdtlist_ = java.util.Collections.unmodifiableList(dmnpdtlist_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_DmnResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_DmnResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kr.wise.advisor.prepare.domain.grpc.DmnResponse.class, kr.wise.advisor.prepare.domain.grpc.DmnResponse.Builder.class);
  }

  public static final int DMNPDTLIST_FIELD_NUMBER = 1;
  private java.util.List<kr.wise.advisor.prepare.domain.grpc.DmnPredictResult> dmnpdtlist_;
  /**
   * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
   */
  public java.util.List<kr.wise.advisor.prepare.domain.grpc.DmnPredictResult> getDmnpdtlistList() {
    return dmnpdtlist_;
  }
  /**
   * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
   */
  public java.util.List<? extends kr.wise.advisor.prepare.domain.grpc.DmnPredictResultOrBuilder> 
      getDmnpdtlistOrBuilderList() {
    return dmnpdtlist_;
  }
  /**
   * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
   */
  public int getDmnpdtlistCount() {
    return dmnpdtlist_.size();
  }
  /**
   * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
   */
  public kr.wise.advisor.prepare.domain.grpc.DmnPredictResult getDmnpdtlist(int index) {
    return dmnpdtlist_.get(index);
  }
  /**
   * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
   */
  public kr.wise.advisor.prepare.domain.grpc.DmnPredictResultOrBuilder getDmnpdtlistOrBuilder(
      int index) {
    return dmnpdtlist_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < dmnpdtlist_.size(); i++) {
      output.writeMessage(1, dmnpdtlist_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < dmnpdtlist_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, dmnpdtlist_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kr.wise.advisor.prepare.domain.grpc.DmnResponse)) {
      return super.equals(obj);
    }
    kr.wise.advisor.prepare.domain.grpc.DmnResponse other = (kr.wise.advisor.prepare.domain.grpc.DmnResponse) obj;

    boolean result = true;
    result = result && getDmnpdtlistList()
        .equals(other.getDmnpdtlistList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getDmnpdtlistCount() > 0) {
      hash = (37 * hash) + DMNPDTLIST_FIELD_NUMBER;
      hash = (53 * hash) + getDmnpdtlistList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kr.wise.advisor.prepare.domain.grpc.DmnResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.domain.grpc.DmnResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kr.wise.advisor.prepare.domain.grpc.DmnResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code domain.DmnResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:domain.DmnResponse)
      kr.wise.advisor.prepare.domain.grpc.DmnResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_DmnResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_DmnResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kr.wise.advisor.prepare.domain.grpc.DmnResponse.class, kr.wise.advisor.prepare.domain.grpc.DmnResponse.Builder.class);
    }

    // Construct using kr.wise.advisor.prepare.domain.grpc.DmnResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getDmnpdtlistFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (dmnpdtlistBuilder_ == null) {
        dmnpdtlist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        dmnpdtlistBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_DmnResponse_descriptor;
    }

    public kr.wise.advisor.prepare.domain.grpc.DmnResponse getDefaultInstanceForType() {
      return kr.wise.advisor.prepare.domain.grpc.DmnResponse.getDefaultInstance();
    }

    public kr.wise.advisor.prepare.domain.grpc.DmnResponse build() {
      kr.wise.advisor.prepare.domain.grpc.DmnResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kr.wise.advisor.prepare.domain.grpc.DmnResponse buildPartial() {
      kr.wise.advisor.prepare.domain.grpc.DmnResponse result = new kr.wise.advisor.prepare.domain.grpc.DmnResponse(this);
      int from_bitField0_ = bitField0_;
      if (dmnpdtlistBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          dmnpdtlist_ = java.util.Collections.unmodifiableList(dmnpdtlist_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.dmnpdtlist_ = dmnpdtlist_;
      } else {
        result.dmnpdtlist_ = dmnpdtlistBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kr.wise.advisor.prepare.domain.grpc.DmnResponse) {
        return mergeFrom((kr.wise.advisor.prepare.domain.grpc.DmnResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kr.wise.advisor.prepare.domain.grpc.DmnResponse other) {
      if (other == kr.wise.advisor.prepare.domain.grpc.DmnResponse.getDefaultInstance()) return this;
      if (dmnpdtlistBuilder_ == null) {
        if (!other.dmnpdtlist_.isEmpty()) {
          if (dmnpdtlist_.isEmpty()) {
            dmnpdtlist_ = other.dmnpdtlist_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureDmnpdtlistIsMutable();
            dmnpdtlist_.addAll(other.dmnpdtlist_);
          }
          onChanged();
        }
      } else {
        if (!other.dmnpdtlist_.isEmpty()) {
          if (dmnpdtlistBuilder_.isEmpty()) {
            dmnpdtlistBuilder_.dispose();
            dmnpdtlistBuilder_ = null;
            dmnpdtlist_ = other.dmnpdtlist_;
            bitField0_ = (bitField0_ & ~0x00000001);
            dmnpdtlistBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getDmnpdtlistFieldBuilder() : null;
          } else {
            dmnpdtlistBuilder_.addAllMessages(other.dmnpdtlist_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kr.wise.advisor.prepare.domain.grpc.DmnResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kr.wise.advisor.prepare.domain.grpc.DmnResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<kr.wise.advisor.prepare.domain.grpc.DmnPredictResult> dmnpdtlist_ =
      java.util.Collections.emptyList();
    private void ensureDmnpdtlistIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        dmnpdtlist_ = new java.util.ArrayList<kr.wise.advisor.prepare.domain.grpc.DmnPredictResult>(dmnpdtlist_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        kr.wise.advisor.prepare.domain.grpc.DmnPredictResult, kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.Builder, kr.wise.advisor.prepare.domain.grpc.DmnPredictResultOrBuilder> dmnpdtlistBuilder_;

    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public java.util.List<kr.wise.advisor.prepare.domain.grpc.DmnPredictResult> getDmnpdtlistList() {
      if (dmnpdtlistBuilder_ == null) {
        return java.util.Collections.unmodifiableList(dmnpdtlist_);
      } else {
        return dmnpdtlistBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public int getDmnpdtlistCount() {
      if (dmnpdtlistBuilder_ == null) {
        return dmnpdtlist_.size();
      } else {
        return dmnpdtlistBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public kr.wise.advisor.prepare.domain.grpc.DmnPredictResult getDmnpdtlist(int index) {
      if (dmnpdtlistBuilder_ == null) {
        return dmnpdtlist_.get(index);
      } else {
        return dmnpdtlistBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public Builder setDmnpdtlist(
        int index, kr.wise.advisor.prepare.domain.grpc.DmnPredictResult value) {
      if (dmnpdtlistBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDmnpdtlistIsMutable();
        dmnpdtlist_.set(index, value);
        onChanged();
      } else {
        dmnpdtlistBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public Builder setDmnpdtlist(
        int index, kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.Builder builderForValue) {
      if (dmnpdtlistBuilder_ == null) {
        ensureDmnpdtlistIsMutable();
        dmnpdtlist_.set(index, builderForValue.build());
        onChanged();
      } else {
        dmnpdtlistBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public Builder addDmnpdtlist(kr.wise.advisor.prepare.domain.grpc.DmnPredictResult value) {
      if (dmnpdtlistBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDmnpdtlistIsMutable();
        dmnpdtlist_.add(value);
        onChanged();
      } else {
        dmnpdtlistBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public Builder addDmnpdtlist(
        int index, kr.wise.advisor.prepare.domain.grpc.DmnPredictResult value) {
      if (dmnpdtlistBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureDmnpdtlistIsMutable();
        dmnpdtlist_.add(index, value);
        onChanged();
      } else {
        dmnpdtlistBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public Builder addDmnpdtlist(
        kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.Builder builderForValue) {
      if (dmnpdtlistBuilder_ == null) {
        ensureDmnpdtlistIsMutable();
        dmnpdtlist_.add(builderForValue.build());
        onChanged();
      } else {
        dmnpdtlistBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public Builder addDmnpdtlist(
        int index, kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.Builder builderForValue) {
      if (dmnpdtlistBuilder_ == null) {
        ensureDmnpdtlistIsMutable();
        dmnpdtlist_.add(index, builderForValue.build());
        onChanged();
      } else {
        dmnpdtlistBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public Builder addAllDmnpdtlist(
        java.lang.Iterable<? extends kr.wise.advisor.prepare.domain.grpc.DmnPredictResult> values) {
      if (dmnpdtlistBuilder_ == null) {
        ensureDmnpdtlistIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, dmnpdtlist_);
        onChanged();
      } else {
        dmnpdtlistBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public Builder clearDmnpdtlist() {
      if (dmnpdtlistBuilder_ == null) {
        dmnpdtlist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        dmnpdtlistBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public Builder removeDmnpdtlist(int index) {
      if (dmnpdtlistBuilder_ == null) {
        ensureDmnpdtlistIsMutable();
        dmnpdtlist_.remove(index);
        onChanged();
      } else {
        dmnpdtlistBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.Builder getDmnpdtlistBuilder(
        int index) {
      return getDmnpdtlistFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public kr.wise.advisor.prepare.domain.grpc.DmnPredictResultOrBuilder getDmnpdtlistOrBuilder(
        int index) {
      if (dmnpdtlistBuilder_ == null) {
        return dmnpdtlist_.get(index);  } else {
        return dmnpdtlistBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public java.util.List<? extends kr.wise.advisor.prepare.domain.grpc.DmnPredictResultOrBuilder> 
         getDmnpdtlistOrBuilderList() {
      if (dmnpdtlistBuilder_ != null) {
        return dmnpdtlistBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(dmnpdtlist_);
      }
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.Builder addDmnpdtlistBuilder() {
      return getDmnpdtlistFieldBuilder().addBuilder(
          kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.getDefaultInstance());
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.Builder addDmnpdtlistBuilder(
        int index) {
      return getDmnpdtlistFieldBuilder().addBuilder(
          index, kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.getDefaultInstance());
    }
    /**
     * <code>repeated .domain.DmnPredictResult dmnpdtlist = 1;</code>
     */
    public java.util.List<kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.Builder> 
         getDmnpdtlistBuilderList() {
      return getDmnpdtlistFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        kr.wise.advisor.prepare.domain.grpc.DmnPredictResult, kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.Builder, kr.wise.advisor.prepare.domain.grpc.DmnPredictResultOrBuilder> 
        getDmnpdtlistFieldBuilder() {
      if (dmnpdtlistBuilder_ == null) {
        dmnpdtlistBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            kr.wise.advisor.prepare.domain.grpc.DmnPredictResult, kr.wise.advisor.prepare.domain.grpc.DmnPredictResult.Builder, kr.wise.advisor.prepare.domain.grpc.DmnPredictResultOrBuilder>(
                dmnpdtlist_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        dmnpdtlist_ = null;
      }
      return dmnpdtlistBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:domain.DmnResponse)
  }

  // @@protoc_insertion_point(class_scope:domain.DmnResponse)
  private static final kr.wise.advisor.prepare.domain.grpc.DmnResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kr.wise.advisor.prepare.domain.grpc.DmnResponse();
  }

  public static kr.wise.advisor.prepare.domain.grpc.DmnResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DmnResponse>
      PARSER = new com.google.protobuf.AbstractParser<DmnResponse>() {
    public DmnResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new DmnResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DmnResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DmnResponse> getParserForType() {
    return PARSER;
  }

  public kr.wise.advisor.prepare.domain.grpc.DmnResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

