// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dmnpredict.proto

package kr.wise.advisor.prepare.domain.grpc;

/**
 * <pre>
 *타겟 DBMS 사용처 : 분석용 테이블의 정보를 처리하기 위한 DB접속정보
 *파이썬에서는 DBMS유형코드에 따라 DB별 접속정보를 생성한다.
 *사용 컬럼 : dbmsTypCd, connTrgLnkUrl, connTrgDrvrNm, dbConnAcId, dbConnAcPwd, dbSchPnm
 *dbSchPnm(DB스키마물리명)이 존재하는 경우 DB접속계정ID와 틀린경우 테이블명 앞에 사용한다. (예: "DB스키마물리명.테이블명")
 * </pre>
 *
 * Protobuf type {@code domain.TargetDbms}
 */
public  final class TargetDbms extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:domain.TargetDbms)
    TargetDbmsOrBuilder {
  // Use TargetDbms.newBuilder() to construct.
  private TargetDbms(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TargetDbms() {
    dbConnTrgId_ = "";
    dbConnTrgPnm_ = "";
    dbConnTrgLnm_ = "";
    dbmsTypCd_ = "";
    dbmsVersCd_ = "";
    connTrgDbLnkChrw_ = "";
    connTrgLnkUrl_ = "";
    connTrgDrvrNm_ = "";
    dbConnAcId_ = "";
    dbConnAcPwd_ = "";
    dbSchId_ = "";
    dbSchPnm_ = "";
    dbSchLnm_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TargetDbms(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            dbConnTrgId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            dbConnTrgPnm_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            dbConnTrgLnm_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            dbmsTypCd_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            dbmsVersCd_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            connTrgDbLnkChrw_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            connTrgLnkUrl_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            connTrgDrvrNm_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            dbConnAcId_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            dbConnAcPwd_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            dbSchId_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            dbSchPnm_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            dbSchLnm_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_TargetDbms_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_TargetDbms_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kr.wise.advisor.prepare.domain.grpc.TargetDbms.class, kr.wise.advisor.prepare.domain.grpc.TargetDbms.Builder.class);
  }

  public static final int DBCONNTRGID_FIELD_NUMBER = 1;
  private volatile java.lang.Object dbConnTrgId_;
  /**
   * <pre>
   *DB접속대상ID
   * </pre>
   *
   * <code>string dbConnTrgId = 1;</code>
   */
  public java.lang.String getDbConnTrgId() {
    java.lang.Object ref = dbConnTrgId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dbConnTrgId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *DB접속대상ID
   * </pre>
   *
   * <code>string dbConnTrgId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getDbConnTrgIdBytes() {
    java.lang.Object ref = dbConnTrgId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dbConnTrgId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DBCONNTRGPNM_FIELD_NUMBER = 2;
  private volatile java.lang.Object dbConnTrgPnm_;
  /**
   * <pre>
   *DB접속대상물리명
   * </pre>
   *
   * <code>string dbConnTrgPnm = 2;</code>
   */
  public java.lang.String getDbConnTrgPnm() {
    java.lang.Object ref = dbConnTrgPnm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dbConnTrgPnm_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *DB접속대상물리명
   * </pre>
   *
   * <code>string dbConnTrgPnm = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDbConnTrgPnmBytes() {
    java.lang.Object ref = dbConnTrgPnm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dbConnTrgPnm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DBCONNTRGLNM_FIELD_NUMBER = 3;
  private volatile java.lang.Object dbConnTrgLnm_;
  /**
   * <pre>
   *DB접속대상논리명
   * </pre>
   *
   * <code>string dbConnTrgLnm = 3;</code>
   */
  public java.lang.String getDbConnTrgLnm() {
    java.lang.Object ref = dbConnTrgLnm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dbConnTrgLnm_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *DB접속대상논리명
   * </pre>
   *
   * <code>string dbConnTrgLnm = 3;</code>
   */
  public com.google.protobuf.ByteString
      getDbConnTrgLnmBytes() {
    java.lang.Object ref = dbConnTrgLnm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dbConnTrgLnm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DBMSTYPCD_FIELD_NUMBER = 4;
  private volatile java.lang.Object dbmsTypCd_;
  /**
   * <pre>
   *DBMS유형코드 (ORA	-ORACLE, SYQ-SYBASEIQ, SYA-SYBASEASE, DB2-DB2, MSQ-MS-SQL, ALT-ALTIBASE, MYS-Mysql)
   * </pre>
   *
   * <code>string dbmsTypCd = 4;</code>
   */
  public java.lang.String getDbmsTypCd() {
    java.lang.Object ref = dbmsTypCd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dbmsTypCd_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *DBMS유형코드 (ORA	-ORACLE, SYQ-SYBASEIQ, SYA-SYBASEASE, DB2-DB2, MSQ-MS-SQL, ALT-ALTIBASE, MYS-Mysql)
   * </pre>
   *
   * <code>string dbmsTypCd = 4;</code>
   */
  public com.google.protobuf.ByteString
      getDbmsTypCdBytes() {
    java.lang.Object ref = dbmsTypCd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dbmsTypCd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DBMSVERSCD_FIELD_NUMBER = 5;
  private volatile java.lang.Object dbmsVersCd_;
  /**
   * <pre>
   *DBMS버전코드
   * </pre>
   *
   * <code>string dbmsVersCd = 5;</code>
   */
  public java.lang.String getDbmsVersCd() {
    java.lang.Object ref = dbmsVersCd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dbmsVersCd_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *DBMS버전코드
   * </pre>
   *
   * <code>string dbmsVersCd = 5;</code>
   */
  public com.google.protobuf.ByteString
      getDbmsVersCdBytes() {
    java.lang.Object ref = dbmsVersCd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dbmsVersCd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONNTRGDBLNKCHRW_FIELD_NUMBER = 6;
  private volatile java.lang.Object connTrgDbLnkChrw_;
  /**
   * <pre>
   *접속대상DB연결문자열
   * </pre>
   *
   * <code>string connTrgDbLnkChrw = 6;</code>
   */
  public java.lang.String getConnTrgDbLnkChrw() {
    java.lang.Object ref = connTrgDbLnkChrw_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      connTrgDbLnkChrw_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *접속대상DB연결문자열
   * </pre>
   *
   * <code>string connTrgDbLnkChrw = 6;</code>
   */
  public com.google.protobuf.ByteString
      getConnTrgDbLnkChrwBytes() {
    java.lang.Object ref = connTrgDbLnkChrw_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      connTrgDbLnkChrw_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONNTRGLNKURL_FIELD_NUMBER = 7;
  private volatile java.lang.Object connTrgLnkUrl_;
  /**
   * <pre>
   *접속대상연결URL
   * </pre>
   *
   * <code>string connTrgLnkUrl = 7;</code>
   */
  public java.lang.String getConnTrgLnkUrl() {
    java.lang.Object ref = connTrgLnkUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      connTrgLnkUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *접속대상연결URL
   * </pre>
   *
   * <code>string connTrgLnkUrl = 7;</code>
   */
  public com.google.protobuf.ByteString
      getConnTrgLnkUrlBytes() {
    java.lang.Object ref = connTrgLnkUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      connTrgLnkUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONNTRGDRVRNM_FIELD_NUMBER = 8;
  private volatile java.lang.Object connTrgDrvrNm_;
  /**
   * <pre>
   *접속대상드라이버명
   * </pre>
   *
   * <code>string connTrgDrvrNm = 8;</code>
   */
  public java.lang.String getConnTrgDrvrNm() {
    java.lang.Object ref = connTrgDrvrNm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      connTrgDrvrNm_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *접속대상드라이버명
   * </pre>
   *
   * <code>string connTrgDrvrNm = 8;</code>
   */
  public com.google.protobuf.ByteString
      getConnTrgDrvrNmBytes() {
    java.lang.Object ref = connTrgDrvrNm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      connTrgDrvrNm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DBCONNACID_FIELD_NUMBER = 9;
  private volatile java.lang.Object dbConnAcId_;
  /**
   * <pre>
   *DB접속계정ID
   * </pre>
   *
   * <code>string dbConnAcId = 9;</code>
   */
  public java.lang.String getDbConnAcId() {
    java.lang.Object ref = dbConnAcId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dbConnAcId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *DB접속계정ID
   * </pre>
   *
   * <code>string dbConnAcId = 9;</code>
   */
  public com.google.protobuf.ByteString
      getDbConnAcIdBytes() {
    java.lang.Object ref = dbConnAcId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dbConnAcId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DBCONNACPWD_FIELD_NUMBER = 10;
  private volatile java.lang.Object dbConnAcPwd_;
  /**
   * <pre>
   *DB접속계정비밀번호
   * </pre>
   *
   * <code>string dbConnAcPwd = 10;</code>
   */
  public java.lang.String getDbConnAcPwd() {
    java.lang.Object ref = dbConnAcPwd_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dbConnAcPwd_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *DB접속계정비밀번호
   * </pre>
   *
   * <code>string dbConnAcPwd = 10;</code>
   */
  public com.google.protobuf.ByteString
      getDbConnAcPwdBytes() {
    java.lang.Object ref = dbConnAcPwd_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dbConnAcPwd_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DBSCHID_FIELD_NUMBER = 11;
  private volatile java.lang.Object dbSchId_;
  /**
   * <pre>
   *DB스키마ID
   * </pre>
   *
   * <code>string dbSchId = 11;</code>
   */
  public java.lang.String getDbSchId() {
    java.lang.Object ref = dbSchId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dbSchId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *DB스키마ID
   * </pre>
   *
   * <code>string dbSchId = 11;</code>
   */
  public com.google.protobuf.ByteString
      getDbSchIdBytes() {
    java.lang.Object ref = dbSchId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dbSchId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DBSCHPNM_FIELD_NUMBER = 12;
  private volatile java.lang.Object dbSchPnm_;
  /**
   * <pre>
   *DB스키마물리명
   * </pre>
   *
   * <code>string dbSchPnm = 12;</code>
   */
  public java.lang.String getDbSchPnm() {
    java.lang.Object ref = dbSchPnm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dbSchPnm_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *DB스키마물리명
   * </pre>
   *
   * <code>string dbSchPnm = 12;</code>
   */
  public com.google.protobuf.ByteString
      getDbSchPnmBytes() {
    java.lang.Object ref = dbSchPnm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dbSchPnm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DBSCHLNM_FIELD_NUMBER = 13;
  private volatile java.lang.Object dbSchLnm_;
  /**
   * <pre>
   *DB스키마논리명
   * </pre>
   *
   * <code>string dbSchLnm = 13;</code>
   */
  public java.lang.String getDbSchLnm() {
    java.lang.Object ref = dbSchLnm_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dbSchLnm_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *DB스키마논리명
   * </pre>
   *
   * <code>string dbSchLnm = 13;</code>
   */
  public com.google.protobuf.ByteString
      getDbSchLnmBytes() {
    java.lang.Object ref = dbSchLnm_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dbSchLnm_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getDbConnTrgIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dbConnTrgId_);
    }
    if (!getDbConnTrgPnmBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, dbConnTrgPnm_);
    }
    if (!getDbConnTrgLnmBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dbConnTrgLnm_);
    }
    if (!getDbmsTypCdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, dbmsTypCd_);
    }
    if (!getDbmsVersCdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, dbmsVersCd_);
    }
    if (!getConnTrgDbLnkChrwBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, connTrgDbLnkChrw_);
    }
    if (!getConnTrgLnkUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, connTrgLnkUrl_);
    }
    if (!getConnTrgDrvrNmBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, connTrgDrvrNm_);
    }
    if (!getDbConnAcIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, dbConnAcId_);
    }
    if (!getDbConnAcPwdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, dbConnAcPwd_);
    }
    if (!getDbSchIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, dbSchId_);
    }
    if (!getDbSchPnmBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, dbSchPnm_);
    }
    if (!getDbSchLnmBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, dbSchLnm_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getDbConnTrgIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dbConnTrgId_);
    }
    if (!getDbConnTrgPnmBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, dbConnTrgPnm_);
    }
    if (!getDbConnTrgLnmBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dbConnTrgLnm_);
    }
    if (!getDbmsTypCdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, dbmsTypCd_);
    }
    if (!getDbmsVersCdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, dbmsVersCd_);
    }
    if (!getConnTrgDbLnkChrwBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, connTrgDbLnkChrw_);
    }
    if (!getConnTrgLnkUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, connTrgLnkUrl_);
    }
    if (!getConnTrgDrvrNmBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, connTrgDrvrNm_);
    }
    if (!getDbConnAcIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, dbConnAcId_);
    }
    if (!getDbConnAcPwdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, dbConnAcPwd_);
    }
    if (!getDbSchIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, dbSchId_);
    }
    if (!getDbSchPnmBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, dbSchPnm_);
    }
    if (!getDbSchLnmBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, dbSchLnm_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kr.wise.advisor.prepare.domain.grpc.TargetDbms)) {
      return super.equals(obj);
    }
    kr.wise.advisor.prepare.domain.grpc.TargetDbms other = (kr.wise.advisor.prepare.domain.grpc.TargetDbms) obj;

    boolean result = true;
    result = result && getDbConnTrgId()
        .equals(other.getDbConnTrgId());
    result = result && getDbConnTrgPnm()
        .equals(other.getDbConnTrgPnm());
    result = result && getDbConnTrgLnm()
        .equals(other.getDbConnTrgLnm());
    result = result && getDbmsTypCd()
        .equals(other.getDbmsTypCd());
    result = result && getDbmsVersCd()
        .equals(other.getDbmsVersCd());
    result = result && getConnTrgDbLnkChrw()
        .equals(other.getConnTrgDbLnkChrw());
    result = result && getConnTrgLnkUrl()
        .equals(other.getConnTrgLnkUrl());
    result = result && getConnTrgDrvrNm()
        .equals(other.getConnTrgDrvrNm());
    result = result && getDbConnAcId()
        .equals(other.getDbConnAcId());
    result = result && getDbConnAcPwd()
        .equals(other.getDbConnAcPwd());
    result = result && getDbSchId()
        .equals(other.getDbSchId());
    result = result && getDbSchPnm()
        .equals(other.getDbSchPnm());
    result = result && getDbSchLnm()
        .equals(other.getDbSchLnm());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DBCONNTRGID_FIELD_NUMBER;
    hash = (53 * hash) + getDbConnTrgId().hashCode();
    hash = (37 * hash) + DBCONNTRGPNM_FIELD_NUMBER;
    hash = (53 * hash) + getDbConnTrgPnm().hashCode();
    hash = (37 * hash) + DBCONNTRGLNM_FIELD_NUMBER;
    hash = (53 * hash) + getDbConnTrgLnm().hashCode();
    hash = (37 * hash) + DBMSTYPCD_FIELD_NUMBER;
    hash = (53 * hash) + getDbmsTypCd().hashCode();
    hash = (37 * hash) + DBMSVERSCD_FIELD_NUMBER;
    hash = (53 * hash) + getDbmsVersCd().hashCode();
    hash = (37 * hash) + CONNTRGDBLNKCHRW_FIELD_NUMBER;
    hash = (53 * hash) + getConnTrgDbLnkChrw().hashCode();
    hash = (37 * hash) + CONNTRGLNKURL_FIELD_NUMBER;
    hash = (53 * hash) + getConnTrgLnkUrl().hashCode();
    hash = (37 * hash) + CONNTRGDRVRNM_FIELD_NUMBER;
    hash = (53 * hash) + getConnTrgDrvrNm().hashCode();
    hash = (37 * hash) + DBCONNACID_FIELD_NUMBER;
    hash = (53 * hash) + getDbConnAcId().hashCode();
    hash = (37 * hash) + DBCONNACPWD_FIELD_NUMBER;
    hash = (53 * hash) + getDbConnAcPwd().hashCode();
    hash = (37 * hash) + DBSCHID_FIELD_NUMBER;
    hash = (53 * hash) + getDbSchId().hashCode();
    hash = (37 * hash) + DBSCHPNM_FIELD_NUMBER;
    hash = (53 * hash) + getDbSchPnm().hashCode();
    hash = (37 * hash) + DBSCHLNM_FIELD_NUMBER;
    hash = (53 * hash) + getDbSchLnm().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kr.wise.advisor.prepare.domain.grpc.TargetDbms parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.domain.grpc.TargetDbms parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.TargetDbms parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.domain.grpc.TargetDbms parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.TargetDbms parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.domain.grpc.TargetDbms parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.TargetDbms parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.domain.grpc.TargetDbms parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.TargetDbms parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.domain.grpc.TargetDbms parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.domain.grpc.TargetDbms parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.domain.grpc.TargetDbms parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kr.wise.advisor.prepare.domain.grpc.TargetDbms prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *타겟 DBMS 사용처 : 분석용 테이블의 정보를 처리하기 위한 DB접속정보
   *파이썬에서는 DBMS유형코드에 따라 DB별 접속정보를 생성한다.
   *사용 컬럼 : dbmsTypCd, connTrgLnkUrl, connTrgDrvrNm, dbConnAcId, dbConnAcPwd, dbSchPnm
   *dbSchPnm(DB스키마물리명)이 존재하는 경우 DB접속계정ID와 틀린경우 테이블명 앞에 사용한다. (예: "DB스키마물리명.테이블명")
   * </pre>
   *
   * Protobuf type {@code domain.TargetDbms}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:domain.TargetDbms)
      kr.wise.advisor.prepare.domain.grpc.TargetDbmsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_TargetDbms_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_TargetDbms_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kr.wise.advisor.prepare.domain.grpc.TargetDbms.class, kr.wise.advisor.prepare.domain.grpc.TargetDbms.Builder.class);
    }

    // Construct using kr.wise.advisor.prepare.domain.grpc.TargetDbms.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      dbConnTrgId_ = "";

      dbConnTrgPnm_ = "";

      dbConnTrgLnm_ = "";

      dbmsTypCd_ = "";

      dbmsVersCd_ = "";

      connTrgDbLnkChrw_ = "";

      connTrgLnkUrl_ = "";

      connTrgDrvrNm_ = "";

      dbConnAcId_ = "";

      dbConnAcPwd_ = "";

      dbSchId_ = "";

      dbSchPnm_ = "";

      dbSchLnm_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kr.wise.advisor.prepare.domain.grpc.DmnPredictProcess.internal_static_domain_TargetDbms_descriptor;
    }

    public kr.wise.advisor.prepare.domain.grpc.TargetDbms getDefaultInstanceForType() {
      return kr.wise.advisor.prepare.domain.grpc.TargetDbms.getDefaultInstance();
    }

    public kr.wise.advisor.prepare.domain.grpc.TargetDbms build() {
      kr.wise.advisor.prepare.domain.grpc.TargetDbms result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kr.wise.advisor.prepare.domain.grpc.TargetDbms buildPartial() {
      kr.wise.advisor.prepare.domain.grpc.TargetDbms result = new kr.wise.advisor.prepare.domain.grpc.TargetDbms(this);
      result.dbConnTrgId_ = dbConnTrgId_;
      result.dbConnTrgPnm_ = dbConnTrgPnm_;
      result.dbConnTrgLnm_ = dbConnTrgLnm_;
      result.dbmsTypCd_ = dbmsTypCd_;
      result.dbmsVersCd_ = dbmsVersCd_;
      result.connTrgDbLnkChrw_ = connTrgDbLnkChrw_;
      result.connTrgLnkUrl_ = connTrgLnkUrl_;
      result.connTrgDrvrNm_ = connTrgDrvrNm_;
      result.dbConnAcId_ = dbConnAcId_;
      result.dbConnAcPwd_ = dbConnAcPwd_;
      result.dbSchId_ = dbSchId_;
      result.dbSchPnm_ = dbSchPnm_;
      result.dbSchLnm_ = dbSchLnm_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kr.wise.advisor.prepare.domain.grpc.TargetDbms) {
        return mergeFrom((kr.wise.advisor.prepare.domain.grpc.TargetDbms)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kr.wise.advisor.prepare.domain.grpc.TargetDbms other) {
      if (other == kr.wise.advisor.prepare.domain.grpc.TargetDbms.getDefaultInstance()) return this;
      if (!other.getDbConnTrgId().isEmpty()) {
        dbConnTrgId_ = other.dbConnTrgId_;
        onChanged();
      }
      if (!other.getDbConnTrgPnm().isEmpty()) {
        dbConnTrgPnm_ = other.dbConnTrgPnm_;
        onChanged();
      }
      if (!other.getDbConnTrgLnm().isEmpty()) {
        dbConnTrgLnm_ = other.dbConnTrgLnm_;
        onChanged();
      }
      if (!other.getDbmsTypCd().isEmpty()) {
        dbmsTypCd_ = other.dbmsTypCd_;
        onChanged();
      }
      if (!other.getDbmsVersCd().isEmpty()) {
        dbmsVersCd_ = other.dbmsVersCd_;
        onChanged();
      }
      if (!other.getConnTrgDbLnkChrw().isEmpty()) {
        connTrgDbLnkChrw_ = other.connTrgDbLnkChrw_;
        onChanged();
      }
      if (!other.getConnTrgLnkUrl().isEmpty()) {
        connTrgLnkUrl_ = other.connTrgLnkUrl_;
        onChanged();
      }
      if (!other.getConnTrgDrvrNm().isEmpty()) {
        connTrgDrvrNm_ = other.connTrgDrvrNm_;
        onChanged();
      }
      if (!other.getDbConnAcId().isEmpty()) {
        dbConnAcId_ = other.dbConnAcId_;
        onChanged();
      }
      if (!other.getDbConnAcPwd().isEmpty()) {
        dbConnAcPwd_ = other.dbConnAcPwd_;
        onChanged();
      }
      if (!other.getDbSchId().isEmpty()) {
        dbSchId_ = other.dbSchId_;
        onChanged();
      }
      if (!other.getDbSchPnm().isEmpty()) {
        dbSchPnm_ = other.dbSchPnm_;
        onChanged();
      }
      if (!other.getDbSchLnm().isEmpty()) {
        dbSchLnm_ = other.dbSchLnm_;
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kr.wise.advisor.prepare.domain.grpc.TargetDbms parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kr.wise.advisor.prepare.domain.grpc.TargetDbms) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object dbConnTrgId_ = "";
    /**
     * <pre>
     *DB접속대상ID
     * </pre>
     *
     * <code>string dbConnTrgId = 1;</code>
     */
    public java.lang.String getDbConnTrgId() {
      java.lang.Object ref = dbConnTrgId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dbConnTrgId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *DB접속대상ID
     * </pre>
     *
     * <code>string dbConnTrgId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getDbConnTrgIdBytes() {
      java.lang.Object ref = dbConnTrgId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbConnTrgId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *DB접속대상ID
     * </pre>
     *
     * <code>string dbConnTrgId = 1;</code>
     */
    public Builder setDbConnTrgId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dbConnTrgId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB접속대상ID
     * </pre>
     *
     * <code>string dbConnTrgId = 1;</code>
     */
    public Builder clearDbConnTrgId() {
      
      dbConnTrgId_ = getDefaultInstance().getDbConnTrgId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB접속대상ID
     * </pre>
     *
     * <code>string dbConnTrgId = 1;</code>
     */
    public Builder setDbConnTrgIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dbConnTrgId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dbConnTrgPnm_ = "";
    /**
     * <pre>
     *DB접속대상물리명
     * </pre>
     *
     * <code>string dbConnTrgPnm = 2;</code>
     */
    public java.lang.String getDbConnTrgPnm() {
      java.lang.Object ref = dbConnTrgPnm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dbConnTrgPnm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *DB접속대상물리명
     * </pre>
     *
     * <code>string dbConnTrgPnm = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDbConnTrgPnmBytes() {
      java.lang.Object ref = dbConnTrgPnm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbConnTrgPnm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *DB접속대상물리명
     * </pre>
     *
     * <code>string dbConnTrgPnm = 2;</code>
     */
    public Builder setDbConnTrgPnm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dbConnTrgPnm_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB접속대상물리명
     * </pre>
     *
     * <code>string dbConnTrgPnm = 2;</code>
     */
    public Builder clearDbConnTrgPnm() {
      
      dbConnTrgPnm_ = getDefaultInstance().getDbConnTrgPnm();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB접속대상물리명
     * </pre>
     *
     * <code>string dbConnTrgPnm = 2;</code>
     */
    public Builder setDbConnTrgPnmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dbConnTrgPnm_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dbConnTrgLnm_ = "";
    /**
     * <pre>
     *DB접속대상논리명
     * </pre>
     *
     * <code>string dbConnTrgLnm = 3;</code>
     */
    public java.lang.String getDbConnTrgLnm() {
      java.lang.Object ref = dbConnTrgLnm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dbConnTrgLnm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *DB접속대상논리명
     * </pre>
     *
     * <code>string dbConnTrgLnm = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDbConnTrgLnmBytes() {
      java.lang.Object ref = dbConnTrgLnm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbConnTrgLnm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *DB접속대상논리명
     * </pre>
     *
     * <code>string dbConnTrgLnm = 3;</code>
     */
    public Builder setDbConnTrgLnm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dbConnTrgLnm_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB접속대상논리명
     * </pre>
     *
     * <code>string dbConnTrgLnm = 3;</code>
     */
    public Builder clearDbConnTrgLnm() {
      
      dbConnTrgLnm_ = getDefaultInstance().getDbConnTrgLnm();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB접속대상논리명
     * </pre>
     *
     * <code>string dbConnTrgLnm = 3;</code>
     */
    public Builder setDbConnTrgLnmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dbConnTrgLnm_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dbmsTypCd_ = "";
    /**
     * <pre>
     *DBMS유형코드 (ORA	-ORACLE, SYQ-SYBASEIQ, SYA-SYBASEASE, DB2-DB2, MSQ-MS-SQL, ALT-ALTIBASE, MYS-Mysql)
     * </pre>
     *
     * <code>string dbmsTypCd = 4;</code>
     */
    public java.lang.String getDbmsTypCd() {
      java.lang.Object ref = dbmsTypCd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dbmsTypCd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *DBMS유형코드 (ORA	-ORACLE, SYQ-SYBASEIQ, SYA-SYBASEASE, DB2-DB2, MSQ-MS-SQL, ALT-ALTIBASE, MYS-Mysql)
     * </pre>
     *
     * <code>string dbmsTypCd = 4;</code>
     */
    public com.google.protobuf.ByteString
        getDbmsTypCdBytes() {
      java.lang.Object ref = dbmsTypCd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbmsTypCd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *DBMS유형코드 (ORA	-ORACLE, SYQ-SYBASEIQ, SYA-SYBASEASE, DB2-DB2, MSQ-MS-SQL, ALT-ALTIBASE, MYS-Mysql)
     * </pre>
     *
     * <code>string dbmsTypCd = 4;</code>
     */
    public Builder setDbmsTypCd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dbmsTypCd_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DBMS유형코드 (ORA	-ORACLE, SYQ-SYBASEIQ, SYA-SYBASEASE, DB2-DB2, MSQ-MS-SQL, ALT-ALTIBASE, MYS-Mysql)
     * </pre>
     *
     * <code>string dbmsTypCd = 4;</code>
     */
    public Builder clearDbmsTypCd() {
      
      dbmsTypCd_ = getDefaultInstance().getDbmsTypCd();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DBMS유형코드 (ORA	-ORACLE, SYQ-SYBASEIQ, SYA-SYBASEASE, DB2-DB2, MSQ-MS-SQL, ALT-ALTIBASE, MYS-Mysql)
     * </pre>
     *
     * <code>string dbmsTypCd = 4;</code>
     */
    public Builder setDbmsTypCdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dbmsTypCd_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dbmsVersCd_ = "";
    /**
     * <pre>
     *DBMS버전코드
     * </pre>
     *
     * <code>string dbmsVersCd = 5;</code>
     */
    public java.lang.String getDbmsVersCd() {
      java.lang.Object ref = dbmsVersCd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dbmsVersCd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *DBMS버전코드
     * </pre>
     *
     * <code>string dbmsVersCd = 5;</code>
     */
    public com.google.protobuf.ByteString
        getDbmsVersCdBytes() {
      java.lang.Object ref = dbmsVersCd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbmsVersCd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *DBMS버전코드
     * </pre>
     *
     * <code>string dbmsVersCd = 5;</code>
     */
    public Builder setDbmsVersCd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dbmsVersCd_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DBMS버전코드
     * </pre>
     *
     * <code>string dbmsVersCd = 5;</code>
     */
    public Builder clearDbmsVersCd() {
      
      dbmsVersCd_ = getDefaultInstance().getDbmsVersCd();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DBMS버전코드
     * </pre>
     *
     * <code>string dbmsVersCd = 5;</code>
     */
    public Builder setDbmsVersCdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dbmsVersCd_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object connTrgDbLnkChrw_ = "";
    /**
     * <pre>
     *접속대상DB연결문자열
     * </pre>
     *
     * <code>string connTrgDbLnkChrw = 6;</code>
     */
    public java.lang.String getConnTrgDbLnkChrw() {
      java.lang.Object ref = connTrgDbLnkChrw_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connTrgDbLnkChrw_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *접속대상DB연결문자열
     * </pre>
     *
     * <code>string connTrgDbLnkChrw = 6;</code>
     */
    public com.google.protobuf.ByteString
        getConnTrgDbLnkChrwBytes() {
      java.lang.Object ref = connTrgDbLnkChrw_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connTrgDbLnkChrw_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *접속대상DB연결문자열
     * </pre>
     *
     * <code>string connTrgDbLnkChrw = 6;</code>
     */
    public Builder setConnTrgDbLnkChrw(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      connTrgDbLnkChrw_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *접속대상DB연결문자열
     * </pre>
     *
     * <code>string connTrgDbLnkChrw = 6;</code>
     */
    public Builder clearConnTrgDbLnkChrw() {
      
      connTrgDbLnkChrw_ = getDefaultInstance().getConnTrgDbLnkChrw();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *접속대상DB연결문자열
     * </pre>
     *
     * <code>string connTrgDbLnkChrw = 6;</code>
     */
    public Builder setConnTrgDbLnkChrwBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      connTrgDbLnkChrw_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object connTrgLnkUrl_ = "";
    /**
     * <pre>
     *접속대상연결URL
     * </pre>
     *
     * <code>string connTrgLnkUrl = 7;</code>
     */
    public java.lang.String getConnTrgLnkUrl() {
      java.lang.Object ref = connTrgLnkUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connTrgLnkUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *접속대상연결URL
     * </pre>
     *
     * <code>string connTrgLnkUrl = 7;</code>
     */
    public com.google.protobuf.ByteString
        getConnTrgLnkUrlBytes() {
      java.lang.Object ref = connTrgLnkUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connTrgLnkUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *접속대상연결URL
     * </pre>
     *
     * <code>string connTrgLnkUrl = 7;</code>
     */
    public Builder setConnTrgLnkUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      connTrgLnkUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *접속대상연결URL
     * </pre>
     *
     * <code>string connTrgLnkUrl = 7;</code>
     */
    public Builder clearConnTrgLnkUrl() {
      
      connTrgLnkUrl_ = getDefaultInstance().getConnTrgLnkUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *접속대상연결URL
     * </pre>
     *
     * <code>string connTrgLnkUrl = 7;</code>
     */
    public Builder setConnTrgLnkUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      connTrgLnkUrl_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object connTrgDrvrNm_ = "";
    /**
     * <pre>
     *접속대상드라이버명
     * </pre>
     *
     * <code>string connTrgDrvrNm = 8;</code>
     */
    public java.lang.String getConnTrgDrvrNm() {
      java.lang.Object ref = connTrgDrvrNm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        connTrgDrvrNm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *접속대상드라이버명
     * </pre>
     *
     * <code>string connTrgDrvrNm = 8;</code>
     */
    public com.google.protobuf.ByteString
        getConnTrgDrvrNmBytes() {
      java.lang.Object ref = connTrgDrvrNm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        connTrgDrvrNm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *접속대상드라이버명
     * </pre>
     *
     * <code>string connTrgDrvrNm = 8;</code>
     */
    public Builder setConnTrgDrvrNm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      connTrgDrvrNm_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *접속대상드라이버명
     * </pre>
     *
     * <code>string connTrgDrvrNm = 8;</code>
     */
    public Builder clearConnTrgDrvrNm() {
      
      connTrgDrvrNm_ = getDefaultInstance().getConnTrgDrvrNm();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *접속대상드라이버명
     * </pre>
     *
     * <code>string connTrgDrvrNm = 8;</code>
     */
    public Builder setConnTrgDrvrNmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      connTrgDrvrNm_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dbConnAcId_ = "";
    /**
     * <pre>
     *DB접속계정ID
     * </pre>
     *
     * <code>string dbConnAcId = 9;</code>
     */
    public java.lang.String getDbConnAcId() {
      java.lang.Object ref = dbConnAcId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dbConnAcId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *DB접속계정ID
     * </pre>
     *
     * <code>string dbConnAcId = 9;</code>
     */
    public com.google.protobuf.ByteString
        getDbConnAcIdBytes() {
      java.lang.Object ref = dbConnAcId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbConnAcId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *DB접속계정ID
     * </pre>
     *
     * <code>string dbConnAcId = 9;</code>
     */
    public Builder setDbConnAcId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dbConnAcId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB접속계정ID
     * </pre>
     *
     * <code>string dbConnAcId = 9;</code>
     */
    public Builder clearDbConnAcId() {
      
      dbConnAcId_ = getDefaultInstance().getDbConnAcId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB접속계정ID
     * </pre>
     *
     * <code>string dbConnAcId = 9;</code>
     */
    public Builder setDbConnAcIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dbConnAcId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dbConnAcPwd_ = "";
    /**
     * <pre>
     *DB접속계정비밀번호
     * </pre>
     *
     * <code>string dbConnAcPwd = 10;</code>
     */
    public java.lang.String getDbConnAcPwd() {
      java.lang.Object ref = dbConnAcPwd_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dbConnAcPwd_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *DB접속계정비밀번호
     * </pre>
     *
     * <code>string dbConnAcPwd = 10;</code>
     */
    public com.google.protobuf.ByteString
        getDbConnAcPwdBytes() {
      java.lang.Object ref = dbConnAcPwd_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbConnAcPwd_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *DB접속계정비밀번호
     * </pre>
     *
     * <code>string dbConnAcPwd = 10;</code>
     */
    public Builder setDbConnAcPwd(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dbConnAcPwd_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB접속계정비밀번호
     * </pre>
     *
     * <code>string dbConnAcPwd = 10;</code>
     */
    public Builder clearDbConnAcPwd() {
      
      dbConnAcPwd_ = getDefaultInstance().getDbConnAcPwd();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB접속계정비밀번호
     * </pre>
     *
     * <code>string dbConnAcPwd = 10;</code>
     */
    public Builder setDbConnAcPwdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dbConnAcPwd_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dbSchId_ = "";
    /**
     * <pre>
     *DB스키마ID
     * </pre>
     *
     * <code>string dbSchId = 11;</code>
     */
    public java.lang.String getDbSchId() {
      java.lang.Object ref = dbSchId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dbSchId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *DB스키마ID
     * </pre>
     *
     * <code>string dbSchId = 11;</code>
     */
    public com.google.protobuf.ByteString
        getDbSchIdBytes() {
      java.lang.Object ref = dbSchId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbSchId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *DB스키마ID
     * </pre>
     *
     * <code>string dbSchId = 11;</code>
     */
    public Builder setDbSchId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dbSchId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB스키마ID
     * </pre>
     *
     * <code>string dbSchId = 11;</code>
     */
    public Builder clearDbSchId() {
      
      dbSchId_ = getDefaultInstance().getDbSchId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB스키마ID
     * </pre>
     *
     * <code>string dbSchId = 11;</code>
     */
    public Builder setDbSchIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dbSchId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dbSchPnm_ = "";
    /**
     * <pre>
     *DB스키마물리명
     * </pre>
     *
     * <code>string dbSchPnm = 12;</code>
     */
    public java.lang.String getDbSchPnm() {
      java.lang.Object ref = dbSchPnm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dbSchPnm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *DB스키마물리명
     * </pre>
     *
     * <code>string dbSchPnm = 12;</code>
     */
    public com.google.protobuf.ByteString
        getDbSchPnmBytes() {
      java.lang.Object ref = dbSchPnm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbSchPnm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *DB스키마물리명
     * </pre>
     *
     * <code>string dbSchPnm = 12;</code>
     */
    public Builder setDbSchPnm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dbSchPnm_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB스키마물리명
     * </pre>
     *
     * <code>string dbSchPnm = 12;</code>
     */
    public Builder clearDbSchPnm() {
      
      dbSchPnm_ = getDefaultInstance().getDbSchPnm();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB스키마물리명
     * </pre>
     *
     * <code>string dbSchPnm = 12;</code>
     */
    public Builder setDbSchPnmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dbSchPnm_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object dbSchLnm_ = "";
    /**
     * <pre>
     *DB스키마논리명
     * </pre>
     *
     * <code>string dbSchLnm = 13;</code>
     */
    public java.lang.String getDbSchLnm() {
      java.lang.Object ref = dbSchLnm_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dbSchLnm_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *DB스키마논리명
     * </pre>
     *
     * <code>string dbSchLnm = 13;</code>
     */
    public com.google.protobuf.ByteString
        getDbSchLnmBytes() {
      java.lang.Object ref = dbSchLnm_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dbSchLnm_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *DB스키마논리명
     * </pre>
     *
     * <code>string dbSchLnm = 13;</code>
     */
    public Builder setDbSchLnm(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      dbSchLnm_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB스키마논리명
     * </pre>
     *
     * <code>string dbSchLnm = 13;</code>
     */
    public Builder clearDbSchLnm() {
      
      dbSchLnm_ = getDefaultInstance().getDbSchLnm();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *DB스키마논리명
     * </pre>
     *
     * <code>string dbSchLnm = 13;</code>
     */
    public Builder setDbSchLnmBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      dbSchLnm_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:domain.TargetDbms)
  }

  // @@protoc_insertion_point(class_scope:domain.TargetDbms)
  private static final kr.wise.advisor.prepare.domain.grpc.TargetDbms DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kr.wise.advisor.prepare.domain.grpc.TargetDbms();
  }

  public static kr.wise.advisor.prepare.domain.grpc.TargetDbms getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TargetDbms>
      PARSER = new com.google.protobuf.AbstractParser<TargetDbms>() {
    public TargetDbms parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TargetDbms(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TargetDbms> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TargetDbms> getParserForType() {
    return PARSER;
  }

  public kr.wise.advisor.prepare.domain.grpc.TargetDbms getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

