// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texthandling.proto

package kr.wise.advisor.prepare.textcluster.grpc;

public interface txtClstrRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kr.wise.advisor.prepare.textcluster.txtClstrRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tableName = 1;</code>
   */
  java.lang.String getTableName();
  /**
   * <code>string tableName = 1;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <code>string col_name = 2;</code>
   */
  java.lang.String getColName();
  /**
   * <code>string col_name = 2;</code>
   */
  com.google.protobuf.ByteString
      getColNameBytes();

  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 3;</code>
   */
  boolean hasTgtDbms();
  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 3;</code>
   */
  kr.wise.advisor.prepare.summary.grpc.TargetDbms getTgtDbms();
  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 3;</code>
   */
  kr.wise.advisor.prepare.summary.grpc.TargetDbmsOrBuilder getTgtDbmsOrBuilder();
}
