// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texthandling.proto

package kr.wise.advisor.prepare.textcluster.grpc;

public interface txtClstrResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kr.wise.advisor.prepare.textcluster.txtClstrResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtClstr txtClstr = 1;</code>
   */
  java.util.List<kr.wise.advisor.prepare.textcluster.grpc.TxtClstr> 
      getTxtClstrList();
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtClstr txtClstr = 1;</code>
   */
  kr.wise.advisor.prepare.textcluster.grpc.TxtClstr getTxtClstr(int index);
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtClstr txtClstr = 1;</code>
   */
  int getTxtClstrCount();
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtClstr txtClstr = 1;</code>
   */
  java.util.List<? extends kr.wise.advisor.prepare.textcluster.grpc.TxtClstrOrBuilder> 
      getTxtClstrOrBuilderList();
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtClstr txtClstr = 1;</code>
   */
  kr.wise.advisor.prepare.textcluster.grpc.TxtClstrOrBuilder getTxtClstrOrBuilder(
      int index);
}
