// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texthandling.proto

package kr.wise.advisor.prepare.textcluster.grpc;

public interface TxtClstrOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kr.wise.advisor.prepare.textcluster.TxtClstr)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string recommand = 1;</code>
   */
  java.lang.String getRecommand();
  /**
   * <code>string recommand = 1;</code>
   */
  com.google.protobuf.ByteString
      getRecommandBytes();

  /**
   * <code>repeated string result = 2;</code>
   */
  java.util.List<java.lang.String>
      getResultList();
  /**
   * <code>repeated string result = 2;</code>
   */
  int getResultCount();
  /**
   * <code>repeated string result = 2;</code>
   */
  java.lang.String getResult(int index);
  /**
   * <code>repeated string result = 2;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes(int index);
}
