// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texthandling.proto

package kr.wise.advisor.prepare.textcluster.grpc;

public interface txtMchResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kr.wise.advisor.prepare.textcluster.txtMchResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch txtMch = 1;</code>
   */
  java.util.List<kr.wise.advisor.prepare.textcluster.grpc.TxtMch> 
      getTxtMchList();
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch txtMch = 1;</code>
   */
  kr.wise.advisor.prepare.textcluster.grpc.TxtMch getTxtMch(int index);
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch txtMch = 1;</code>
   */
  int getTxtMchCount();
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch txtMch = 1;</code>
   */
  java.util.List<? extends kr.wise.advisor.prepare.textcluster.grpc.TxtMchOrBuilder> 
      getTxtMchOrBuilderList();
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch txtMch = 1;</code>
   */
  kr.wise.advisor.prepare.textcluster.grpc.TxtMchOrBuilder getTxtMchOrBuilder(
      int index);
}
