// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texthandling.proto

package kr.wise.advisor.prepare.textcluster.grpc;

/**
 * Protobuf type {@code kr.wise.advisor.prepare.textcluster.txtMchResponse}
 */
public  final class txtMchResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kr.wise.advisor.prepare.textcluster.txtMchResponse)
    txtMchResponseOrBuilder {
  // Use txtMchResponse.newBuilder() to construct.
  private txtMchResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private txtMchResponse() {
    colVal_ = java.util.Collections.emptyList();
    result_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private txtMchResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              colVal_ = new java.util.ArrayList<kr.wise.advisor.prepare.textcluster.grpc.TxtMch>();
              mutable_bitField0_ |= 0x00000001;
            }
            colVal_.add(
                input.readMessage(kr.wise.advisor.prepare.textcluster.grpc.TxtMch.parser(), extensionRegistry));
            break;
          }
          case 18: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              result_ = new java.util.ArrayList<kr.wise.advisor.prepare.textcluster.grpc.txtMchResult>();
              mutable_bitField0_ |= 0x00000002;
            }
            result_.add(
                input.readMessage(kr.wise.advisor.prepare.textcluster.grpc.txtMchResult.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        colVal_ = java.util.Collections.unmodifiableList(colVal_);
      }
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        result_ = java.util.Collections.unmodifiableList(result_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kr.wise.advisor.prepare.textcluster.grpc.TextProcess.internal_static_kr_wise_advisor_prepare_textcluster_txtMchResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kr.wise.advisor.prepare.textcluster.grpc.TextProcess.internal_static_kr_wise_advisor_prepare_textcluster_txtMchResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse.class, kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse.Builder.class);
  }

  public static final int COLVAL_FIELD_NUMBER = 1;
  private java.util.List<kr.wise.advisor.prepare.textcluster.grpc.TxtMch> colVal_;
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
   */
  public java.util.List<kr.wise.advisor.prepare.textcluster.grpc.TxtMch> getColValList() {
    return colVal_;
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
   */
  public java.util.List<? extends kr.wise.advisor.prepare.textcluster.grpc.TxtMchOrBuilder> 
      getColValOrBuilderList() {
    return colVal_;
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
   */
  public int getColValCount() {
    return colVal_.size();
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
   */
  public kr.wise.advisor.prepare.textcluster.grpc.TxtMch getColVal(int index) {
    return colVal_.get(index);
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
   */
  public kr.wise.advisor.prepare.textcluster.grpc.TxtMchOrBuilder getColValOrBuilder(
      int index) {
    return colVal_.get(index);
  }

  public static final int RESULT_FIELD_NUMBER = 2;
  private java.util.List<kr.wise.advisor.prepare.textcluster.grpc.txtMchResult> result_;
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
   */
  public java.util.List<kr.wise.advisor.prepare.textcluster.grpc.txtMchResult> getResultList() {
    return result_;
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
   */
  public java.util.List<? extends kr.wise.advisor.prepare.textcluster.grpc.txtMchResultOrBuilder> 
      getResultOrBuilderList() {
    return result_;
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
   */
  public int getResultCount() {
    return result_.size();
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
   */
  public kr.wise.advisor.prepare.textcluster.grpc.txtMchResult getResult(int index) {
    return result_.get(index);
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
   */
  public kr.wise.advisor.prepare.textcluster.grpc.txtMchResultOrBuilder getResultOrBuilder(
      int index) {
    return result_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < colVal_.size(); i++) {
      output.writeMessage(1, colVal_.get(i));
    }
    for (int i = 0; i < result_.size(); i++) {
      output.writeMessage(2, result_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < colVal_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, colVal_.get(i));
    }
    for (int i = 0; i < result_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, result_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse)) {
      return super.equals(obj);
    }
    kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse other = (kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse) obj;

    boolean result = true;
    result = result && getColValList()
        .equals(other.getColValList());
    result = result && getResultList()
        .equals(other.getResultList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getColValCount() > 0) {
      hash = (37 * hash) + COLVAL_FIELD_NUMBER;
      hash = (53 * hash) + getColValList().hashCode();
    }
    if (getResultCount() > 0) {
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResultList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kr.wise.advisor.prepare.textcluster.txtMchResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kr.wise.advisor.prepare.textcluster.txtMchResponse)
      kr.wise.advisor.prepare.textcluster.grpc.txtMchResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kr.wise.advisor.prepare.textcluster.grpc.TextProcess.internal_static_kr_wise_advisor_prepare_textcluster_txtMchResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kr.wise.advisor.prepare.textcluster.grpc.TextProcess.internal_static_kr_wise_advisor_prepare_textcluster_txtMchResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse.class, kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse.Builder.class);
    }

    // Construct using kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getColValFieldBuilder();
        getResultFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (colValBuilder_ == null) {
        colVal_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        colValBuilder_.clear();
      }
      if (resultBuilder_ == null) {
        result_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
      } else {
        resultBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kr.wise.advisor.prepare.textcluster.grpc.TextProcess.internal_static_kr_wise_advisor_prepare_textcluster_txtMchResponse_descriptor;
    }

    public kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse getDefaultInstanceForType() {
      return kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse.getDefaultInstance();
    }

    public kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse build() {
      kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse buildPartial() {
      kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse result = new kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse(this);
      int from_bitField0_ = bitField0_;
      if (colValBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          colVal_ = java.util.Collections.unmodifiableList(colVal_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.colVal_ = colVal_;
      } else {
        result.colVal_ = colValBuilder_.build();
      }
      if (resultBuilder_ == null) {
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          result_ = java.util.Collections.unmodifiableList(result_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.result_ = result_;
      } else {
        result.result_ = resultBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse) {
        return mergeFrom((kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse other) {
      if (other == kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse.getDefaultInstance()) return this;
      if (colValBuilder_ == null) {
        if (!other.colVal_.isEmpty()) {
          if (colVal_.isEmpty()) {
            colVal_ = other.colVal_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureColValIsMutable();
            colVal_.addAll(other.colVal_);
          }
          onChanged();
        }
      } else {
        if (!other.colVal_.isEmpty()) {
          if (colValBuilder_.isEmpty()) {
            colValBuilder_.dispose();
            colValBuilder_ = null;
            colVal_ = other.colVal_;
            bitField0_ = (bitField0_ & ~0x00000001);
            colValBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getColValFieldBuilder() : null;
          } else {
            colValBuilder_.addAllMessages(other.colVal_);
          }
        }
      }
      if (resultBuilder_ == null) {
        if (!other.result_.isEmpty()) {
          if (result_.isEmpty()) {
            result_ = other.result_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureResultIsMutable();
            result_.addAll(other.result_);
          }
          onChanged();
        }
      } else {
        if (!other.result_.isEmpty()) {
          if (resultBuilder_.isEmpty()) {
            resultBuilder_.dispose();
            resultBuilder_ = null;
            result_ = other.result_;
            bitField0_ = (bitField0_ & ~0x00000002);
            resultBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResultFieldBuilder() : null;
          } else {
            resultBuilder_.addAllMessages(other.result_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<kr.wise.advisor.prepare.textcluster.grpc.TxtMch> colVal_ =
      java.util.Collections.emptyList();
    private void ensureColValIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        colVal_ = new java.util.ArrayList<kr.wise.advisor.prepare.textcluster.grpc.TxtMch>(colVal_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        kr.wise.advisor.prepare.textcluster.grpc.TxtMch, kr.wise.advisor.prepare.textcluster.grpc.TxtMch.Builder, kr.wise.advisor.prepare.textcluster.grpc.TxtMchOrBuilder> colValBuilder_;

    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public java.util.List<kr.wise.advisor.prepare.textcluster.grpc.TxtMch> getColValList() {
      if (colValBuilder_ == null) {
        return java.util.Collections.unmodifiableList(colVal_);
      } else {
        return colValBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public int getColValCount() {
      if (colValBuilder_ == null) {
        return colVal_.size();
      } else {
        return colValBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public kr.wise.advisor.prepare.textcluster.grpc.TxtMch getColVal(int index) {
      if (colValBuilder_ == null) {
        return colVal_.get(index);
      } else {
        return colValBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public Builder setColVal(
        int index, kr.wise.advisor.prepare.textcluster.grpc.TxtMch value) {
      if (colValBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColValIsMutable();
        colVal_.set(index, value);
        onChanged();
      } else {
        colValBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public Builder setColVal(
        int index, kr.wise.advisor.prepare.textcluster.grpc.TxtMch.Builder builderForValue) {
      if (colValBuilder_ == null) {
        ensureColValIsMutable();
        colVal_.set(index, builderForValue.build());
        onChanged();
      } else {
        colValBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public Builder addColVal(kr.wise.advisor.prepare.textcluster.grpc.TxtMch value) {
      if (colValBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColValIsMutable();
        colVal_.add(value);
        onChanged();
      } else {
        colValBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public Builder addColVal(
        int index, kr.wise.advisor.prepare.textcluster.grpc.TxtMch value) {
      if (colValBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureColValIsMutable();
        colVal_.add(index, value);
        onChanged();
      } else {
        colValBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public Builder addColVal(
        kr.wise.advisor.prepare.textcluster.grpc.TxtMch.Builder builderForValue) {
      if (colValBuilder_ == null) {
        ensureColValIsMutable();
        colVal_.add(builderForValue.build());
        onChanged();
      } else {
        colValBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public Builder addColVal(
        int index, kr.wise.advisor.prepare.textcluster.grpc.TxtMch.Builder builderForValue) {
      if (colValBuilder_ == null) {
        ensureColValIsMutable();
        colVal_.add(index, builderForValue.build());
        onChanged();
      } else {
        colValBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public Builder addAllColVal(
        java.lang.Iterable<? extends kr.wise.advisor.prepare.textcluster.grpc.TxtMch> values) {
      if (colValBuilder_ == null) {
        ensureColValIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, colVal_);
        onChanged();
      } else {
        colValBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public Builder clearColVal() {
      if (colValBuilder_ == null) {
        colVal_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        colValBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public Builder removeColVal(int index) {
      if (colValBuilder_ == null) {
        ensureColValIsMutable();
        colVal_.remove(index);
        onChanged();
      } else {
        colValBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public kr.wise.advisor.prepare.textcluster.grpc.TxtMch.Builder getColValBuilder(
        int index) {
      return getColValFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public kr.wise.advisor.prepare.textcluster.grpc.TxtMchOrBuilder getColValOrBuilder(
        int index) {
      if (colValBuilder_ == null) {
        return colVal_.get(index);  } else {
        return colValBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public java.util.List<? extends kr.wise.advisor.prepare.textcluster.grpc.TxtMchOrBuilder> 
         getColValOrBuilderList() {
      if (colValBuilder_ != null) {
        return colValBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(colVal_);
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public kr.wise.advisor.prepare.textcluster.grpc.TxtMch.Builder addColValBuilder() {
      return getColValFieldBuilder().addBuilder(
          kr.wise.advisor.prepare.textcluster.grpc.TxtMch.getDefaultInstance());
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public kr.wise.advisor.prepare.textcluster.grpc.TxtMch.Builder addColValBuilder(
        int index) {
      return getColValFieldBuilder().addBuilder(
          index, kr.wise.advisor.prepare.textcluster.grpc.TxtMch.getDefaultInstance());
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.TxtMch colVal = 1;</code>
     */
    public java.util.List<kr.wise.advisor.prepare.textcluster.grpc.TxtMch.Builder> 
         getColValBuilderList() {
      return getColValFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        kr.wise.advisor.prepare.textcluster.grpc.TxtMch, kr.wise.advisor.prepare.textcluster.grpc.TxtMch.Builder, kr.wise.advisor.prepare.textcluster.grpc.TxtMchOrBuilder> 
        getColValFieldBuilder() {
      if (colValBuilder_ == null) {
        colValBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            kr.wise.advisor.prepare.textcluster.grpc.TxtMch, kr.wise.advisor.prepare.textcluster.grpc.TxtMch.Builder, kr.wise.advisor.prepare.textcluster.grpc.TxtMchOrBuilder>(
                colVal_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        colVal_ = null;
      }
      return colValBuilder_;
    }

    private java.util.List<kr.wise.advisor.prepare.textcluster.grpc.txtMchResult> result_ =
      java.util.Collections.emptyList();
    private void ensureResultIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        result_ = new java.util.ArrayList<kr.wise.advisor.prepare.textcluster.grpc.txtMchResult>(result_);
        bitField0_ |= 0x00000002;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        kr.wise.advisor.prepare.textcluster.grpc.txtMchResult, kr.wise.advisor.prepare.textcluster.grpc.txtMchResult.Builder, kr.wise.advisor.prepare.textcluster.grpc.txtMchResultOrBuilder> resultBuilder_;

    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public java.util.List<kr.wise.advisor.prepare.textcluster.grpc.txtMchResult> getResultList() {
      if (resultBuilder_ == null) {
        return java.util.Collections.unmodifiableList(result_);
      } else {
        return resultBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public int getResultCount() {
      if (resultBuilder_ == null) {
        return result_.size();
      } else {
        return resultBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public kr.wise.advisor.prepare.textcluster.grpc.txtMchResult getResult(int index) {
      if (resultBuilder_ == null) {
        return result_.get(index);
      } else {
        return resultBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public Builder setResult(
        int index, kr.wise.advisor.prepare.textcluster.grpc.txtMchResult value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultIsMutable();
        result_.set(index, value);
        onChanged();
      } else {
        resultBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public Builder setResult(
        int index, kr.wise.advisor.prepare.textcluster.grpc.txtMchResult.Builder builderForValue) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public Builder addResult(kr.wise.advisor.prepare.textcluster.grpc.txtMchResult value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultIsMutable();
        result_.add(value);
        onChanged();
      } else {
        resultBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public Builder addResult(
        int index, kr.wise.advisor.prepare.textcluster.grpc.txtMchResult value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultIsMutable();
        result_.add(index, value);
        onChanged();
      } else {
        resultBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public Builder addResult(
        kr.wise.advisor.prepare.textcluster.grpc.txtMchResult.Builder builderForValue) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.add(builderForValue.build());
        onChanged();
      } else {
        resultBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public Builder addResult(
        int index, kr.wise.advisor.prepare.textcluster.grpc.txtMchResult.Builder builderForValue) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public Builder addAllResult(
        java.lang.Iterable<? extends kr.wise.advisor.prepare.textcluster.grpc.txtMchResult> values) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, result_);
        onChanged();
      } else {
        resultBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public Builder clearResult() {
      if (resultBuilder_ == null) {
        result_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
      } else {
        resultBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public Builder removeResult(int index) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.remove(index);
        onChanged();
      } else {
        resultBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public kr.wise.advisor.prepare.textcluster.grpc.txtMchResult.Builder getResultBuilder(
        int index) {
      return getResultFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public kr.wise.advisor.prepare.textcluster.grpc.txtMchResultOrBuilder getResultOrBuilder(
        int index) {
      if (resultBuilder_ == null) {
        return result_.get(index);  } else {
        return resultBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public java.util.List<? extends kr.wise.advisor.prepare.textcluster.grpc.txtMchResultOrBuilder> 
         getResultOrBuilderList() {
      if (resultBuilder_ != null) {
        return resultBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(result_);
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public kr.wise.advisor.prepare.textcluster.grpc.txtMchResult.Builder addResultBuilder() {
      return getResultFieldBuilder().addBuilder(
          kr.wise.advisor.prepare.textcluster.grpc.txtMchResult.getDefaultInstance());
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public kr.wise.advisor.prepare.textcluster.grpc.txtMchResult.Builder addResultBuilder(
        int index) {
      return getResultFieldBuilder().addBuilder(
          index, kr.wise.advisor.prepare.textcluster.grpc.txtMchResult.getDefaultInstance());
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.textcluster.txtMchResult result = 2;</code>
     */
    public java.util.List<kr.wise.advisor.prepare.textcluster.grpc.txtMchResult.Builder> 
         getResultBuilderList() {
      return getResultFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        kr.wise.advisor.prepare.textcluster.grpc.txtMchResult, kr.wise.advisor.prepare.textcluster.grpc.txtMchResult.Builder, kr.wise.advisor.prepare.textcluster.grpc.txtMchResultOrBuilder> 
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            kr.wise.advisor.prepare.textcluster.grpc.txtMchResult, kr.wise.advisor.prepare.textcluster.grpc.txtMchResult.Builder, kr.wise.advisor.prepare.textcluster.grpc.txtMchResultOrBuilder>(
                result_,
                ((bitField0_ & 0x00000002) == 0x00000002),
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      return resultBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:kr.wise.advisor.prepare.textcluster.txtMchResponse)
  }

  // @@protoc_insertion_point(class_scope:kr.wise.advisor.prepare.textcluster.txtMchResponse)
  private static final kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse();
  }

  public static kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<txtMchResponse>
      PARSER = new com.google.protobuf.AbstractParser<txtMchResponse>() {
    public txtMchResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new txtMchResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<txtMchResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<txtMchResponse> getParserForType() {
    return PARSER;
  }

  public kr.wise.advisor.prepare.textcluster.grpc.txtMchResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

