// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texthandling.proto

package kr.wise.advisor.prepare.textcluster.grpc;

public interface txtMchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kr.wise.advisor.prepare.textcluster.txtMchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.kr.wise.advisor.prepare.textcluster.InfoDb sourceTb = 1;</code>
   */
  boolean hasSourceTb();
  /**
   * <code>.kr.wise.advisor.prepare.textcluster.InfoDb sourceTb = 1;</code>
   */
  kr.wise.advisor.prepare.textcluster.grpc.InfoDb getSourceTb();
  /**
   * <code>.kr.wise.advisor.prepare.textcluster.InfoDb sourceTb = 1;</code>
   */
  kr.wise.advisor.prepare.textcluster.grpc.InfoDbOrBuilder getSourceTbOrBuilder();

  /**
   * <code>.kr.wise.advisor.prepare.textcluster.InfoDb targetTb = 2;</code>
   */
  boolean hasTargetTb();
  /**
   * <code>.kr.wise.advisor.prepare.textcluster.InfoDb targetTb = 2;</code>
   */
  kr.wise.advisor.prepare.textcluster.grpc.InfoDb getTargetTb();
  /**
   * <code>.kr.wise.advisor.prepare.textcluster.InfoDb targetTb = 2;</code>
   */
  kr.wise.advisor.prepare.textcluster.grpc.InfoDbOrBuilder getTargetTbOrBuilder();

  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 3;</code>
   */
  boolean hasTgtDbms();
  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 3;</code>
   */
  kr.wise.advisor.prepare.summary.grpc.TargetDbms getTgtDbms();
  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 3;</code>
   */
  kr.wise.advisor.prepare.summary.grpc.TargetDbmsOrBuilder getTgtDbmsOrBuilder();
}
