// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: texthandling.proto

package kr.wise.advisor.prepare.textcluster.grpc;

/**
 * Protobuf type {@code kr.wise.advisor.prepare.textcluster.TxtMch}
 */
public  final class TxtMch extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kr.wise.advisor.prepare.textcluster.TxtMch)
    TxtMchOrBuilder {
  // Use TxtMch.newBuilder() to construct.
  private TxtMch(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private TxtMch() {
    colVal_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    similarity_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private TxtMch(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              colVal_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            colVal_.add(s);
            break;
          }
          case 21: {

            similarity_ = input.readFloat();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        colVal_ = colVal_.getUnmodifiableView();
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kr.wise.advisor.prepare.textcluster.grpc.TextProcess.internal_static_kr_wise_advisor_prepare_textcluster_TxtMch_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kr.wise.advisor.prepare.textcluster.grpc.TextProcess.internal_static_kr_wise_advisor_prepare_textcluster_TxtMch_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kr.wise.advisor.prepare.textcluster.grpc.TxtMch.class, kr.wise.advisor.prepare.textcluster.grpc.TxtMch.Builder.class);
  }

  private int bitField0_;
  public static final int COL_VAL_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList colVal_;
  /**
   * <code>repeated string col_val = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getColValList() {
    return colVal_;
  }
  /**
   * <code>repeated string col_val = 1;</code>
   */
  public int getColValCount() {
    return colVal_.size();
  }
  /**
   * <code>repeated string col_val = 1;</code>
   */
  public java.lang.String getColVal(int index) {
    return colVal_.get(index);
  }
  /**
   * <code>repeated string col_val = 1;</code>
   */
  public com.google.protobuf.ByteString
      getColValBytes(int index) {
    return colVal_.getByteString(index);
  }

  public static final int SIMILARITY_FIELD_NUMBER = 2;
  private float similarity_;
  /**
   * <code>float similarity = 2;</code>
   */
  public float getSimilarity() {
    return similarity_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < colVal_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, colVal_.getRaw(i));
    }
    if (similarity_ != 0F) {
      output.writeFloat(2, similarity_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < colVal_.size(); i++) {
        dataSize += computeStringSizeNoTag(colVal_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getColValList().size();
    }
    if (similarity_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, similarity_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kr.wise.advisor.prepare.textcluster.grpc.TxtMch)) {
      return super.equals(obj);
    }
    kr.wise.advisor.prepare.textcluster.grpc.TxtMch other = (kr.wise.advisor.prepare.textcluster.grpc.TxtMch) obj;

    boolean result = true;
    result = result && getColValList()
        .equals(other.getColValList());
    result = result && (
        java.lang.Float.floatToIntBits(getSimilarity())
        == java.lang.Float.floatToIntBits(
            other.getSimilarity()));
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getColValCount() > 0) {
      hash = (37 * hash) + COL_VAL_FIELD_NUMBER;
      hash = (53 * hash) + getColValList().hashCode();
    }
    hash = (37 * hash) + SIMILARITY_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getSimilarity());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kr.wise.advisor.prepare.textcluster.grpc.TxtMch parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.TxtMch parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.TxtMch parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.TxtMch parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.TxtMch parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.TxtMch parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.TxtMch parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.TxtMch parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.TxtMch parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.TxtMch parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.TxtMch parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.textcluster.grpc.TxtMch parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kr.wise.advisor.prepare.textcluster.grpc.TxtMch prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kr.wise.advisor.prepare.textcluster.TxtMch}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kr.wise.advisor.prepare.textcluster.TxtMch)
      kr.wise.advisor.prepare.textcluster.grpc.TxtMchOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kr.wise.advisor.prepare.textcluster.grpc.TextProcess.internal_static_kr_wise_advisor_prepare_textcluster_TxtMch_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kr.wise.advisor.prepare.textcluster.grpc.TextProcess.internal_static_kr_wise_advisor_prepare_textcluster_TxtMch_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kr.wise.advisor.prepare.textcluster.grpc.TxtMch.class, kr.wise.advisor.prepare.textcluster.grpc.TxtMch.Builder.class);
    }

    // Construct using kr.wise.advisor.prepare.textcluster.grpc.TxtMch.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      colVal_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      similarity_ = 0F;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kr.wise.advisor.prepare.textcluster.grpc.TextProcess.internal_static_kr_wise_advisor_prepare_textcluster_TxtMch_descriptor;
    }

    public kr.wise.advisor.prepare.textcluster.grpc.TxtMch getDefaultInstanceForType() {
      return kr.wise.advisor.prepare.textcluster.grpc.TxtMch.getDefaultInstance();
    }

    public kr.wise.advisor.prepare.textcluster.grpc.TxtMch build() {
      kr.wise.advisor.prepare.textcluster.grpc.TxtMch result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kr.wise.advisor.prepare.textcluster.grpc.TxtMch buildPartial() {
      kr.wise.advisor.prepare.textcluster.grpc.TxtMch result = new kr.wise.advisor.prepare.textcluster.grpc.TxtMch(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        colVal_ = colVal_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.colVal_ = colVal_;
      result.similarity_ = similarity_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kr.wise.advisor.prepare.textcluster.grpc.TxtMch) {
        return mergeFrom((kr.wise.advisor.prepare.textcluster.grpc.TxtMch)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kr.wise.advisor.prepare.textcluster.grpc.TxtMch other) {
      if (other == kr.wise.advisor.prepare.textcluster.grpc.TxtMch.getDefaultInstance()) return this;
      if (!other.colVal_.isEmpty()) {
        if (colVal_.isEmpty()) {
          colVal_ = other.colVal_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureColValIsMutable();
          colVal_.addAll(other.colVal_);
        }
        onChanged();
      }
      if (other.getSimilarity() != 0F) {
        setSimilarity(other.getSimilarity());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kr.wise.advisor.prepare.textcluster.grpc.TxtMch parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kr.wise.advisor.prepare.textcluster.grpc.TxtMch) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList colVal_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureColValIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        colVal_ = new com.google.protobuf.LazyStringArrayList(colVal_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string col_val = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getColValList() {
      return colVal_.getUnmodifiableView();
    }
    /**
     * <code>repeated string col_val = 1;</code>
     */
    public int getColValCount() {
      return colVal_.size();
    }
    /**
     * <code>repeated string col_val = 1;</code>
     */
    public java.lang.String getColVal(int index) {
      return colVal_.get(index);
    }
    /**
     * <code>repeated string col_val = 1;</code>
     */
    public com.google.protobuf.ByteString
        getColValBytes(int index) {
      return colVal_.getByteString(index);
    }
    /**
     * <code>repeated string col_val = 1;</code>
     */
    public Builder setColVal(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureColValIsMutable();
      colVal_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string col_val = 1;</code>
     */
    public Builder addColVal(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureColValIsMutable();
      colVal_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string col_val = 1;</code>
     */
    public Builder addAllColVal(
        java.lang.Iterable<java.lang.String> values) {
      ensureColValIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, colVal_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string col_val = 1;</code>
     */
    public Builder clearColVal() {
      colVal_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string col_val = 1;</code>
     */
    public Builder addColValBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureColValIsMutable();
      colVal_.add(value);
      onChanged();
      return this;
    }

    private float similarity_ ;
    /**
     * <code>float similarity = 2;</code>
     */
    public float getSimilarity() {
      return similarity_;
    }
    /**
     * <code>float similarity = 2;</code>
     */
    public Builder setSimilarity(float value) {
      
      similarity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float similarity = 2;</code>
     */
    public Builder clearSimilarity() {
      
      similarity_ = 0F;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:kr.wise.advisor.prepare.textcluster.TxtMch)
  }

  // @@protoc_insertion_point(class_scope:kr.wise.advisor.prepare.textcluster.TxtMch)
  private static final kr.wise.advisor.prepare.textcluster.grpc.TxtMch DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kr.wise.advisor.prepare.textcluster.grpc.TxtMch();
  }

  public static kr.wise.advisor.prepare.textcluster.grpc.TxtMch getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<TxtMch>
      PARSER = new com.google.protobuf.AbstractParser<TxtMch>() {
    public TxtMch parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new TxtMch(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<TxtMch> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<TxtMch> getParserForType() {
    return PARSER;
  }

  public kr.wise.advisor.prepare.textcluster.grpc.TxtMch getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

