// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: summary.proto

package kr.wise.advisor.prepare.summary.grpc;

public interface ColRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kr.wise.advisor.prepare.summary.ColRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *테이블명
   * </pre>
   *
   * <code>string tableName = 1;</code>
   */
  java.lang.String getTableName();
  /**
   * <pre>
   *테이블명
   * </pre>
   *
   * <code>string tableName = 1;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <pre>
   *컬럼명
   * </pre>
   *
   * <code>string colName = 2;</code>
   */
  java.lang.String getColName();
  /**
   * <pre>
   *컬럼명
   * </pre>
   *
   * <code>string colName = 2;</code>
   */
  com.google.protobuf.ByteString
      getColNameBytes();

  /**
   * <pre>
   *변수ID
   * </pre>
   *
   * <code>string varId = 3;</code>
   */
  java.lang.String getVarId();
  /**
   * <pre>
   *변수ID
   * </pre>
   *
   * <code>string varId = 3;</code>
   */
  com.google.protobuf.ByteString
      getVarIdBytes();

  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 4;</code>
   */
  boolean hasTgtDbms();
  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 4;</code>
   */
  kr.wise.advisor.prepare.summary.grpc.TargetDbms getTgtDbms();
  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 4;</code>
   */
  kr.wise.advisor.prepare.summary.grpc.TargetDbmsOrBuilder getTgtDbmsOrBuilder();
}
