// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: summary.proto

package kr.wise.advisor.prepare.summary.grpc;

/**
 * <pre>
 *히스토그램 응답... 컬럼의 히스토그
 * </pre>
 *
 * Protobuf type {@code kr.wise.advisor.prepare.summary.HistResponse}
 */
public  final class HistResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kr.wise.advisor.prepare.summary.HistResponse)
    HistResponseOrBuilder {
  // Use HistResponse.newBuilder() to construct.
  private HistResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private HistResponse() {
    varId_ = "";
    strVal_ = java.util.Collections.emptyList();
    sctVal_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private HistResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            varId_ = s;
            break;
          }
          case 21: {
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
              strVal_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000002;
            }
            strVal_.add(input.readFloat());
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000002) == 0x00000002) && input.getBytesUntilLimit() > 0) {
              strVal_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000002;
            }
            while (input.getBytesUntilLimit() > 0) {
              strVal_.add(input.readFloat());
            }
            input.popLimit(limit);
            break;
          }
          case 29: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              sctVal_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000004;
            }
            sctVal_.add(input.readFloat());
            break;
          }
          case 26: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004) && input.getBytesUntilLimit() > 0) {
              sctVal_ = new java.util.ArrayList<java.lang.Float>();
              mutable_bitField0_ |= 0x00000004;
            }
            while (input.getBytesUntilLimit() > 0) {
              sctVal_.add(input.readFloat());
            }
            input.popLimit(limit);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
        strVal_ = java.util.Collections.unmodifiableList(strVal_);
      }
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        sctVal_ = java.util.Collections.unmodifiableList(sctVal_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kr.wise.advisor.prepare.summary.grpc.SummaryProcess.internal_static_kr_wise_advisor_prepare_summary_HistResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kr.wise.advisor.prepare.summary.grpc.SummaryProcess.internal_static_kr_wise_advisor_prepare_summary_HistResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kr.wise.advisor.prepare.summary.grpc.HistResponse.class, kr.wise.advisor.prepare.summary.grpc.HistResponse.Builder.class);
  }

  private int bitField0_;
  public static final int VARID_FIELD_NUMBER = 1;
  private volatile java.lang.Object varId_;
  /**
   * <pre>
   *변수ID : HistRequest의 변수ID를 리턴한다.
   * </pre>
   *
   * <code>string varId = 1;</code>
   */
  public java.lang.String getVarId() {
    java.lang.Object ref = varId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      varId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *변수ID : HistRequest의 변수ID를 리턴한다.
   * </pre>
   *
   * <code>string varId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getVarIdBytes() {
    java.lang.Object ref = varId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      varId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STRVAL_FIELD_NUMBER = 2;
  private java.util.List<java.lang.Float> strVal_;
  /**
   * <pre>
   *구간시작값
   * </pre>
   *
   * <code>repeated float strVal = 2;</code>
   */
  public java.util.List<java.lang.Float>
      getStrValList() {
    return strVal_;
  }
  /**
   * <pre>
   *구간시작값
   * </pre>
   *
   * <code>repeated float strVal = 2;</code>
   */
  public int getStrValCount() {
    return strVal_.size();
  }
  /**
   * <pre>
   *구간시작값
   * </pre>
   *
   * <code>repeated float strVal = 2;</code>
   */
  public float getStrVal(int index) {
    return strVal_.get(index);
  }
  private int strValMemoizedSerializedSize = -1;

  public static final int SCTVAL_FIELD_NUMBER = 3;
  private java.util.List<java.lang.Float> sctVal_;
  /**
   * <pre>
   *구간 카운터 수
   * </pre>
   *
   * <code>repeated float sctVal = 3;</code>
   */
  public java.util.List<java.lang.Float>
      getSctValList() {
    return sctVal_;
  }
  /**
   * <pre>
   *구간 카운터 수
   * </pre>
   *
   * <code>repeated float sctVal = 3;</code>
   */
  public int getSctValCount() {
    return sctVal_.size();
  }
  /**
   * <pre>
   *구간 카운터 수
   * </pre>
   *
   * <code>repeated float sctVal = 3;</code>
   */
  public float getSctVal(int index) {
    return sctVal_.get(index);
  }
  private int sctValMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (!getVarIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, varId_);
    }
    if (getStrValList().size() > 0) {
      output.writeUInt32NoTag(18);
      output.writeUInt32NoTag(strValMemoizedSerializedSize);
    }
    for (int i = 0; i < strVal_.size(); i++) {
      output.writeFloatNoTag(strVal_.get(i));
    }
    if (getSctValList().size() > 0) {
      output.writeUInt32NoTag(26);
      output.writeUInt32NoTag(sctValMemoizedSerializedSize);
    }
    for (int i = 0; i < sctVal_.size(); i++) {
      output.writeFloatNoTag(sctVal_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getVarIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, varId_);
    }
    {
      int dataSize = 0;
      dataSize = 4 * getStrValList().size();
      size += dataSize;
      if (!getStrValList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      strValMemoizedSerializedSize = dataSize;
    }
    {
      int dataSize = 0;
      dataSize = 4 * getSctValList().size();
      size += dataSize;
      if (!getSctValList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      sctValMemoizedSerializedSize = dataSize;
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kr.wise.advisor.prepare.summary.grpc.HistResponse)) {
      return super.equals(obj);
    }
    kr.wise.advisor.prepare.summary.grpc.HistResponse other = (kr.wise.advisor.prepare.summary.grpc.HistResponse) obj;

    boolean result = true;
    result = result && getVarId()
        .equals(other.getVarId());
    result = result && getStrValList()
        .equals(other.getStrValList());
    result = result && getSctValList()
        .equals(other.getSctValList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VARID_FIELD_NUMBER;
    hash = (53 * hash) + getVarId().hashCode();
    if (getStrValCount() > 0) {
      hash = (37 * hash) + STRVAL_FIELD_NUMBER;
      hash = (53 * hash) + getStrValList().hashCode();
    }
    if (getSctValCount() > 0) {
      hash = (37 * hash) + SCTVAL_FIELD_NUMBER;
      hash = (53 * hash) + getSctValList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kr.wise.advisor.prepare.summary.grpc.HistResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.summary.grpc.HistResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.summary.grpc.HistResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.summary.grpc.HistResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.summary.grpc.HistResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.summary.grpc.HistResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.summary.grpc.HistResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.summary.grpc.HistResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.summary.grpc.HistResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.summary.grpc.HistResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.summary.grpc.HistResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.summary.grpc.HistResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kr.wise.advisor.prepare.summary.grpc.HistResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *히스토그램 응답... 컬럼의 히스토그
   * </pre>
   *
   * Protobuf type {@code kr.wise.advisor.prepare.summary.HistResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kr.wise.advisor.prepare.summary.HistResponse)
      kr.wise.advisor.prepare.summary.grpc.HistResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kr.wise.advisor.prepare.summary.grpc.SummaryProcess.internal_static_kr_wise_advisor_prepare_summary_HistResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kr.wise.advisor.prepare.summary.grpc.SummaryProcess.internal_static_kr_wise_advisor_prepare_summary_HistResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kr.wise.advisor.prepare.summary.grpc.HistResponse.class, kr.wise.advisor.prepare.summary.grpc.HistResponse.Builder.class);
    }

    // Construct using kr.wise.advisor.prepare.summary.grpc.HistResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      varId_ = "";

      strVal_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      sctVal_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kr.wise.advisor.prepare.summary.grpc.SummaryProcess.internal_static_kr_wise_advisor_prepare_summary_HistResponse_descriptor;
    }

    public kr.wise.advisor.prepare.summary.grpc.HistResponse getDefaultInstanceForType() {
      return kr.wise.advisor.prepare.summary.grpc.HistResponse.getDefaultInstance();
    }

    public kr.wise.advisor.prepare.summary.grpc.HistResponse build() {
      kr.wise.advisor.prepare.summary.grpc.HistResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kr.wise.advisor.prepare.summary.grpc.HistResponse buildPartial() {
      kr.wise.advisor.prepare.summary.grpc.HistResponse result = new kr.wise.advisor.prepare.summary.grpc.HistResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.varId_ = varId_;
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        strVal_ = java.util.Collections.unmodifiableList(strVal_);
        bitField0_ = (bitField0_ & ~0x00000002);
      }
      result.strVal_ = strVal_;
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        sctVal_ = java.util.Collections.unmodifiableList(sctVal_);
        bitField0_ = (bitField0_ & ~0x00000004);
      }
      result.sctVal_ = sctVal_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kr.wise.advisor.prepare.summary.grpc.HistResponse) {
        return mergeFrom((kr.wise.advisor.prepare.summary.grpc.HistResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kr.wise.advisor.prepare.summary.grpc.HistResponse other) {
      if (other == kr.wise.advisor.prepare.summary.grpc.HistResponse.getDefaultInstance()) return this;
      if (!other.getVarId().isEmpty()) {
        varId_ = other.varId_;
        onChanged();
      }
      if (!other.strVal_.isEmpty()) {
        if (strVal_.isEmpty()) {
          strVal_ = other.strVal_;
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          ensureStrValIsMutable();
          strVal_.addAll(other.strVal_);
        }
        onChanged();
      }
      if (!other.sctVal_.isEmpty()) {
        if (sctVal_.isEmpty()) {
          sctVal_ = other.sctVal_;
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          ensureSctValIsMutable();
          sctVal_.addAll(other.sctVal_);
        }
        onChanged();
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kr.wise.advisor.prepare.summary.grpc.HistResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kr.wise.advisor.prepare.summary.grpc.HistResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object varId_ = "";
    /**
     * <pre>
     *변수ID : HistRequest의 변수ID를 리턴한다.
     * </pre>
     *
     * <code>string varId = 1;</code>
     */
    public java.lang.String getVarId() {
      java.lang.Object ref = varId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        varId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *변수ID : HistRequest의 변수ID를 리턴한다.
     * </pre>
     *
     * <code>string varId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getVarIdBytes() {
      java.lang.Object ref = varId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        varId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *변수ID : HistRequest의 변수ID를 리턴한다.
     * </pre>
     *
     * <code>string varId = 1;</code>
     */
    public Builder setVarId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      varId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *변수ID : HistRequest의 변수ID를 리턴한다.
     * </pre>
     *
     * <code>string varId = 1;</code>
     */
    public Builder clearVarId() {
      
      varId_ = getDefaultInstance().getVarId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *변수ID : HistRequest의 변수ID를 리턴한다.
     * </pre>
     *
     * <code>string varId = 1;</code>
     */
    public Builder setVarIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      varId_ = value;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Float> strVal_ = java.util.Collections.emptyList();
    private void ensureStrValIsMutable() {
      if (!((bitField0_ & 0x00000002) == 0x00000002)) {
        strVal_ = new java.util.ArrayList<java.lang.Float>(strVal_);
        bitField0_ |= 0x00000002;
       }
    }
    /**
     * <pre>
     *구간시작값
     * </pre>
     *
     * <code>repeated float strVal = 2;</code>
     */
    public java.util.List<java.lang.Float>
        getStrValList() {
      return java.util.Collections.unmodifiableList(strVal_);
    }
    /**
     * <pre>
     *구간시작값
     * </pre>
     *
     * <code>repeated float strVal = 2;</code>
     */
    public int getStrValCount() {
      return strVal_.size();
    }
    /**
     * <pre>
     *구간시작값
     * </pre>
     *
     * <code>repeated float strVal = 2;</code>
     */
    public float getStrVal(int index) {
      return strVal_.get(index);
    }
    /**
     * <pre>
     *구간시작값
     * </pre>
     *
     * <code>repeated float strVal = 2;</code>
     */
    public Builder setStrVal(
        int index, float value) {
      ensureStrValIsMutable();
      strVal_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *구간시작값
     * </pre>
     *
     * <code>repeated float strVal = 2;</code>
     */
    public Builder addStrVal(float value) {
      ensureStrValIsMutable();
      strVal_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *구간시작값
     * </pre>
     *
     * <code>repeated float strVal = 2;</code>
     */
    public Builder addAllStrVal(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureStrValIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, strVal_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *구간시작값
     * </pre>
     *
     * <code>repeated float strVal = 2;</code>
     */
    public Builder clearStrVal() {
      strVal_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Float> sctVal_ = java.util.Collections.emptyList();
    private void ensureSctValIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        sctVal_ = new java.util.ArrayList<java.lang.Float>(sctVal_);
        bitField0_ |= 0x00000004;
       }
    }
    /**
     * <pre>
     *구간 카운터 수
     * </pre>
     *
     * <code>repeated float sctVal = 3;</code>
     */
    public java.util.List<java.lang.Float>
        getSctValList() {
      return java.util.Collections.unmodifiableList(sctVal_);
    }
    /**
     * <pre>
     *구간 카운터 수
     * </pre>
     *
     * <code>repeated float sctVal = 3;</code>
     */
    public int getSctValCount() {
      return sctVal_.size();
    }
    /**
     * <pre>
     *구간 카운터 수
     * </pre>
     *
     * <code>repeated float sctVal = 3;</code>
     */
    public float getSctVal(int index) {
      return sctVal_.get(index);
    }
    /**
     * <pre>
     *구간 카운터 수
     * </pre>
     *
     * <code>repeated float sctVal = 3;</code>
     */
    public Builder setSctVal(
        int index, float value) {
      ensureSctValIsMutable();
      sctVal_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *구간 카운터 수
     * </pre>
     *
     * <code>repeated float sctVal = 3;</code>
     */
    public Builder addSctVal(float value) {
      ensureSctValIsMutable();
      sctVal_.add(value);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *구간 카운터 수
     * </pre>
     *
     * <code>repeated float sctVal = 3;</code>
     */
    public Builder addAllSctVal(
        java.lang.Iterable<? extends java.lang.Float> values) {
      ensureSctValIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, sctVal_);
      onChanged();
      return this;
    }
    /**
     * <pre>
     *구간 카운터 수
     * </pre>
     *
     * <code>repeated float sctVal = 3;</code>
     */
    public Builder clearSctVal() {
      sctVal_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:kr.wise.advisor.prepare.summary.HistResponse)
  }

  // @@protoc_insertion_point(class_scope:kr.wise.advisor.prepare.summary.HistResponse)
  private static final kr.wise.advisor.prepare.summary.grpc.HistResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kr.wise.advisor.prepare.summary.grpc.HistResponse();
  }

  public static kr.wise.advisor.prepare.summary.grpc.HistResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<HistResponse>
      PARSER = new com.google.protobuf.AbstractParser<HistResponse>() {
    public HistResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new HistResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<HistResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<HistResponse> getParserForType() {
    return PARSER;
  }

  public kr.wise.advisor.prepare.summary.grpc.HistResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

