// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: summary.proto

package kr.wise.advisor.prepare.summary.grpc;

public interface HistResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kr.wise.advisor.prepare.summary.HistResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *변수ID : HistRequest의 변수ID를 리턴한다.
   * </pre>
   *
   * <code>string varId = 1;</code>
   */
  java.lang.String getVarId();
  /**
   * <pre>
   *변수ID : HistRequest의 변수ID를 리턴한다.
   * </pre>
   *
   * <code>string varId = 1;</code>
   */
  com.google.protobuf.ByteString
      getVarIdBytes();

  /**
   * <pre>
   *구간시작값
   * </pre>
   *
   * <code>repeated float strVal = 2;</code>
   */
  java.util.List<java.lang.Float> getStrValList();
  /**
   * <pre>
   *구간시작값
   * </pre>
   *
   * <code>repeated float strVal = 2;</code>
   */
  int getStrValCount();
  /**
   * <pre>
   *구간시작값
   * </pre>
   *
   * <code>repeated float strVal = 2;</code>
   */
  float getStrVal(int index);

  /**
   * <pre>
   *구간 카운터 수
   * </pre>
   *
   * <code>repeated float sctVal = 3;</code>
   */
  java.util.List<java.lang.Float> getSctValList();
  /**
   * <pre>
   *구간 카운터 수
   * </pre>
   *
   * <code>repeated float sctVal = 3;</code>
   */
  int getSctValCount();
  /**
   * <pre>
   *구간 카운터 수
   * </pre>
   *
   * <code>repeated float sctVal = 3;</code>
   */
  float getSctVal(int index);
}
