// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: summary.proto

package kr.wise.advisor.prepare.summary.grpc;

/**
 * Protobuf type {@code kr.wise.advisor.prepare.summary.SummaryReply}
 */
public  final class SummaryReply extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:kr.wise.advisor.prepare.summary.SummaryReply)
    SummaryReplyOrBuilder {
  // Use SummaryReply.newBuilder() to construct.
  private SummaryReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private SummaryReply() {
    summaries_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private SummaryReply(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              summaries_ = new java.util.ArrayList<kr.wise.advisor.prepare.summary.grpc.Summary>();
              mutable_bitField0_ |= 0x00000001;
            }
            summaries_.add(
                input.readMessage(kr.wise.advisor.prepare.summary.grpc.Summary.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        summaries_ = java.util.Collections.unmodifiableList(summaries_);
      }
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return kr.wise.advisor.prepare.summary.grpc.SummaryProcess.internal_static_kr_wise_advisor_prepare_summary_SummaryReply_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return kr.wise.advisor.prepare.summary.grpc.SummaryProcess.internal_static_kr_wise_advisor_prepare_summary_SummaryReply_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            kr.wise.advisor.prepare.summary.grpc.SummaryReply.class, kr.wise.advisor.prepare.summary.grpc.SummaryReply.Builder.class);
  }

  public static final int SUMMARIES_FIELD_NUMBER = 1;
  private java.util.List<kr.wise.advisor.prepare.summary.grpc.Summary> summaries_;
  /**
   * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
   */
  public java.util.List<kr.wise.advisor.prepare.summary.grpc.Summary> getSummariesList() {
    return summaries_;
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
   */
  public java.util.List<? extends kr.wise.advisor.prepare.summary.grpc.SummaryOrBuilder> 
      getSummariesOrBuilderList() {
    return summaries_;
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
   */
  public int getSummariesCount() {
    return summaries_.size();
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
   */
  public kr.wise.advisor.prepare.summary.grpc.Summary getSummaries(int index) {
    return summaries_.get(index);
  }
  /**
   * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
   */
  public kr.wise.advisor.prepare.summary.grpc.SummaryOrBuilder getSummariesOrBuilder(
      int index) {
    return summaries_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < summaries_.size(); i++) {
      output.writeMessage(1, summaries_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < summaries_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, summaries_.get(i));
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof kr.wise.advisor.prepare.summary.grpc.SummaryReply)) {
      return super.equals(obj);
    }
    kr.wise.advisor.prepare.summary.grpc.SummaryReply other = (kr.wise.advisor.prepare.summary.grpc.SummaryReply) obj;

    boolean result = true;
    result = result && getSummariesList()
        .equals(other.getSummariesList());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getSummariesCount() > 0) {
      hash = (37 * hash) + SUMMARIES_FIELD_NUMBER;
      hash = (53 * hash) + getSummariesList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static kr.wise.advisor.prepare.summary.grpc.SummaryReply parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.summary.grpc.SummaryReply parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.summary.grpc.SummaryReply parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.summary.grpc.SummaryReply parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.summary.grpc.SummaryReply parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static kr.wise.advisor.prepare.summary.grpc.SummaryReply parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.summary.grpc.SummaryReply parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.summary.grpc.SummaryReply parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.summary.grpc.SummaryReply parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.summary.grpc.SummaryReply parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static kr.wise.advisor.prepare.summary.grpc.SummaryReply parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static kr.wise.advisor.prepare.summary.grpc.SummaryReply parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(kr.wise.advisor.prepare.summary.grpc.SummaryReply prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code kr.wise.advisor.prepare.summary.SummaryReply}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:kr.wise.advisor.prepare.summary.SummaryReply)
      kr.wise.advisor.prepare.summary.grpc.SummaryReplyOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return kr.wise.advisor.prepare.summary.grpc.SummaryProcess.internal_static_kr_wise_advisor_prepare_summary_SummaryReply_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return kr.wise.advisor.prepare.summary.grpc.SummaryProcess.internal_static_kr_wise_advisor_prepare_summary_SummaryReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              kr.wise.advisor.prepare.summary.grpc.SummaryReply.class, kr.wise.advisor.prepare.summary.grpc.SummaryReply.Builder.class);
    }

    // Construct using kr.wise.advisor.prepare.summary.grpc.SummaryReply.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSummariesFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (summariesBuilder_ == null) {
        summaries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        summariesBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return kr.wise.advisor.prepare.summary.grpc.SummaryProcess.internal_static_kr_wise_advisor_prepare_summary_SummaryReply_descriptor;
    }

    public kr.wise.advisor.prepare.summary.grpc.SummaryReply getDefaultInstanceForType() {
      return kr.wise.advisor.prepare.summary.grpc.SummaryReply.getDefaultInstance();
    }

    public kr.wise.advisor.prepare.summary.grpc.SummaryReply build() {
      kr.wise.advisor.prepare.summary.grpc.SummaryReply result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public kr.wise.advisor.prepare.summary.grpc.SummaryReply buildPartial() {
      kr.wise.advisor.prepare.summary.grpc.SummaryReply result = new kr.wise.advisor.prepare.summary.grpc.SummaryReply(this);
      int from_bitField0_ = bitField0_;
      if (summariesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          summaries_ = java.util.Collections.unmodifiableList(summaries_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.summaries_ = summaries_;
      } else {
        result.summaries_ = summariesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof kr.wise.advisor.prepare.summary.grpc.SummaryReply) {
        return mergeFrom((kr.wise.advisor.prepare.summary.grpc.SummaryReply)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(kr.wise.advisor.prepare.summary.grpc.SummaryReply other) {
      if (other == kr.wise.advisor.prepare.summary.grpc.SummaryReply.getDefaultInstance()) return this;
      if (summariesBuilder_ == null) {
        if (!other.summaries_.isEmpty()) {
          if (summaries_.isEmpty()) {
            summaries_ = other.summaries_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSummariesIsMutable();
            summaries_.addAll(other.summaries_);
          }
          onChanged();
        }
      } else {
        if (!other.summaries_.isEmpty()) {
          if (summariesBuilder_.isEmpty()) {
            summariesBuilder_.dispose();
            summariesBuilder_ = null;
            summaries_ = other.summaries_;
            bitField0_ = (bitField0_ & ~0x00000001);
            summariesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSummariesFieldBuilder() : null;
          } else {
            summariesBuilder_.addAllMessages(other.summaries_);
          }
        }
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      kr.wise.advisor.prepare.summary.grpc.SummaryReply parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (kr.wise.advisor.prepare.summary.grpc.SummaryReply) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<kr.wise.advisor.prepare.summary.grpc.Summary> summaries_ =
      java.util.Collections.emptyList();
    private void ensureSummariesIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        summaries_ = new java.util.ArrayList<kr.wise.advisor.prepare.summary.grpc.Summary>(summaries_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        kr.wise.advisor.prepare.summary.grpc.Summary, kr.wise.advisor.prepare.summary.grpc.Summary.Builder, kr.wise.advisor.prepare.summary.grpc.SummaryOrBuilder> summariesBuilder_;

    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public java.util.List<kr.wise.advisor.prepare.summary.grpc.Summary> getSummariesList() {
      if (summariesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(summaries_);
      } else {
        return summariesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public int getSummariesCount() {
      if (summariesBuilder_ == null) {
        return summaries_.size();
      } else {
        return summariesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public kr.wise.advisor.prepare.summary.grpc.Summary getSummaries(int index) {
      if (summariesBuilder_ == null) {
        return summaries_.get(index);
      } else {
        return summariesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public Builder setSummaries(
        int index, kr.wise.advisor.prepare.summary.grpc.Summary value) {
      if (summariesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSummariesIsMutable();
        summaries_.set(index, value);
        onChanged();
      } else {
        summariesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public Builder setSummaries(
        int index, kr.wise.advisor.prepare.summary.grpc.Summary.Builder builderForValue) {
      if (summariesBuilder_ == null) {
        ensureSummariesIsMutable();
        summaries_.set(index, builderForValue.build());
        onChanged();
      } else {
        summariesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public Builder addSummaries(kr.wise.advisor.prepare.summary.grpc.Summary value) {
      if (summariesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSummariesIsMutable();
        summaries_.add(value);
        onChanged();
      } else {
        summariesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public Builder addSummaries(
        int index, kr.wise.advisor.prepare.summary.grpc.Summary value) {
      if (summariesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSummariesIsMutable();
        summaries_.add(index, value);
        onChanged();
      } else {
        summariesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public Builder addSummaries(
        kr.wise.advisor.prepare.summary.grpc.Summary.Builder builderForValue) {
      if (summariesBuilder_ == null) {
        ensureSummariesIsMutable();
        summaries_.add(builderForValue.build());
        onChanged();
      } else {
        summariesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public Builder addSummaries(
        int index, kr.wise.advisor.prepare.summary.grpc.Summary.Builder builderForValue) {
      if (summariesBuilder_ == null) {
        ensureSummariesIsMutable();
        summaries_.add(index, builderForValue.build());
        onChanged();
      } else {
        summariesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public Builder addAllSummaries(
        java.lang.Iterable<? extends kr.wise.advisor.prepare.summary.grpc.Summary> values) {
      if (summariesBuilder_ == null) {
        ensureSummariesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, summaries_);
        onChanged();
      } else {
        summariesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public Builder clearSummaries() {
      if (summariesBuilder_ == null) {
        summaries_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        summariesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public Builder removeSummaries(int index) {
      if (summariesBuilder_ == null) {
        ensureSummariesIsMutable();
        summaries_.remove(index);
        onChanged();
      } else {
        summariesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public kr.wise.advisor.prepare.summary.grpc.Summary.Builder getSummariesBuilder(
        int index) {
      return getSummariesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public kr.wise.advisor.prepare.summary.grpc.SummaryOrBuilder getSummariesOrBuilder(
        int index) {
      if (summariesBuilder_ == null) {
        return summaries_.get(index);  } else {
        return summariesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public java.util.List<? extends kr.wise.advisor.prepare.summary.grpc.SummaryOrBuilder> 
         getSummariesOrBuilderList() {
      if (summariesBuilder_ != null) {
        return summariesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(summaries_);
      }
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public kr.wise.advisor.prepare.summary.grpc.Summary.Builder addSummariesBuilder() {
      return getSummariesFieldBuilder().addBuilder(
          kr.wise.advisor.prepare.summary.grpc.Summary.getDefaultInstance());
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public kr.wise.advisor.prepare.summary.grpc.Summary.Builder addSummariesBuilder(
        int index) {
      return getSummariesFieldBuilder().addBuilder(
          index, kr.wise.advisor.prepare.summary.grpc.Summary.getDefaultInstance());
    }
    /**
     * <code>repeated .kr.wise.advisor.prepare.summary.Summary summaries = 1;</code>
     */
    public java.util.List<kr.wise.advisor.prepare.summary.grpc.Summary.Builder> 
         getSummariesBuilderList() {
      return getSummariesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        kr.wise.advisor.prepare.summary.grpc.Summary, kr.wise.advisor.prepare.summary.grpc.Summary.Builder, kr.wise.advisor.prepare.summary.grpc.SummaryOrBuilder> 
        getSummariesFieldBuilder() {
      if (summariesBuilder_ == null) {
        summariesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            kr.wise.advisor.prepare.summary.grpc.Summary, kr.wise.advisor.prepare.summary.grpc.Summary.Builder, kr.wise.advisor.prepare.summary.grpc.SummaryOrBuilder>(
                summaries_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        summaries_ = null;
      }
      return summariesBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:kr.wise.advisor.prepare.summary.SummaryReply)
  }

  // @@protoc_insertion_point(class_scope:kr.wise.advisor.prepare.summary.SummaryReply)
  private static final kr.wise.advisor.prepare.summary.grpc.SummaryReply DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new kr.wise.advisor.prepare.summary.grpc.SummaryReply();
  }

  public static kr.wise.advisor.prepare.summary.grpc.SummaryReply getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SummaryReply>
      PARSER = new com.google.protobuf.AbstractParser<SummaryReply>() {
    public SummaryReply parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new SummaryReply(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<SummaryReply> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SummaryReply> getParserForType() {
    return PARSER;
  }

  public kr.wise.advisor.prepare.summary.grpc.SummaryReply getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

