// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: summary.proto

package kr.wise.advisor.prepare.summary.grpc;

public interface SummaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kr.wise.advisor.prepare.summary.Summary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *컬럼명
   * </pre>
   *
   * <code>string name = 13;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *컬럼명
   * </pre>
   *
   * <code>string name = 13;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *전체수
   * </pre>
   *
   * <code>uint32 count = 1;</code>
   */
  int getCount();

  /**
   * <pre>
   *평균
   * </pre>
   *
   * <code>float mean = 2;</code>
   */
  float getMean();

  /**
   * <pre>
   *최소값
   * </pre>
   *
   * <code>float min = 3;</code>
   */
  float getMin();

  /**
   * <pre>
   *표준편차
   * </pre>
   *
   * <code>float std = 4;</code>
   */
  float getStd();

  /**
   * <pre>
   *1분위수
   * </pre>
   *
   * <code>float q1 = 5;</code>
   */
  float getQ1();

  /**
   * <pre>
   *2분위수(중앙값)
   * </pre>
   *
   * <code>float q2 = 6;</code>
   */
  float getQ2();

  /**
   * <pre>
   *3분위수
   * </pre>
   *
   * <code>float q3 = 7;</code>
   */
  float getQ3();

  /**
   * <pre>
   *최대값
   * </pre>
   *
   * <code>float max = 8;</code>
   */
  float getMax();

  /**
   * <pre>
   *유니크수
   * </pre>
   *
   * <code>uint32 unique = 9;</code>
   */
  int getUnique();

  /**
   * <pre>
   *최빈값
   * </pre>
   *
   * <code>string top = 10;</code>
   */
  java.lang.String getTop();
  /**
   * <pre>
   *최빈값
   * </pre>
   *
   * <code>string top = 10;</code>
   */
  com.google.protobuf.ByteString
      getTopBytes();

  /**
   * <pre>
   *최빈값 갯수
   * </pre>
   *
   * <code>uint32 freq = 11;</code>
   */
  int getFreq();

  /**
   * <pre>
   *변수타입
   * </pre>
   *
   * <code>string type = 12;</code>
   */
  java.lang.String getType();
  /**
   * <pre>
   *변수타입
   * </pre>
   *
   * <code>string type = 12;</code>
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
