// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: summary.proto

package kr.wise.advisor.prepare.summary.grpc;

public final class SummaryProcess {
  private SummaryProcess() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kr_wise_advisor_prepare_summary_TableRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kr_wise_advisor_prepare_summary_TableRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kr_wise_advisor_prepare_summary_ColRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kr_wise_advisor_prepare_summary_ColRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kr_wise_advisor_prepare_summary_TargetDbms_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kr_wise_advisor_prepare_summary_TargetDbms_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kr_wise_advisor_prepare_summary_BoxResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kr_wise_advisor_prepare_summary_BoxResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kr_wise_advisor_prepare_summary_SummaryReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kr_wise_advisor_prepare_summary_SummaryReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kr_wise_advisor_prepare_summary_Summary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kr_wise_advisor_prepare_summary_Summary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_kr_wise_advisor_prepare_summary_HistResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_kr_wise_advisor_prepare_summary_HistResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsummary.proto\022\037kr.wise.advisor.prepare" +
      ".summary\"_\n\014TableRequest\022\021\n\ttableName\030\001 " +
      "\001(\t\022<\n\007tgtDbms\030\002 \001(\0132+.kr.wise.advisor.p" +
      "repare.summary.TargetDbms\"}\n\nColRequest\022" +
      "\021\n\ttableName\030\001 \001(\t\022\017\n\007colName\030\002 \001(\t\022\r\n\005v" +
      "arId\030\003 \001(\t\022<\n\007tgtDbms\030\004 \001(\0132+.kr.wise.ad" +
      "visor.prepare.summary.TargetDbms\"\232\002\n\nTar" +
      "getDbms\022\023\n\013dbConnTrgId\030\001 \001(\t\022\024\n\014dbConnTr" +
      "gPnm\030\002 \001(\t\022\024\n\014dbConnTrgLnm\030\003 \001(\t\022\021\n\tdbms" +
      "TypCd\030\004 \001(\t\022\022\n\ndbmsVersCd\030\005 \001(\t\022\030\n\020connT",
      "rgDbLnkChrw\030\006 \001(\t\022\025\n\rconnTrgLnkUrl\030\007 \001(\t" +
      "\022\025\n\rconnTrgDrvrNm\030\010 \001(\t\022\022\n\ndbConnAcId\030\t " +
      "\001(\t\022\023\n\013dbConnAcPwd\030\n \001(\t\022\017\n\007dbSchId\030\013 \001(" +
      "\t\022\020\n\010dbSchPnm\030\014 \001(\t\022\020\n\010dbSchLnm\030\r \001(\t\"g\n" +
      "\013BoxResponse\022\r\n\005varId\030\001 \001(\t\0229\n\007summary\030\002" +
      " \001(\0132(.kr.wise.advisor.prepare.summary.S" +
      "ummary\022\016\n\006outVal\030\003 \003(\002\"K\n\014SummaryReply\022;" +
      "\n\tsummaries\030\001 \003(\0132(.kr.wise.advisor.prep" +
      "are.summary.Summary\"\270\001\n\007Summary\022\014\n\004name\030" +
      "\r \001(\t\022\r\n\005count\030\001 \001(\r\022\014\n\004mean\030\002 \001(\002\022\013\n\003mi",
      "n\030\003 \001(\002\022\013\n\003std\030\004 \001(\002\022\n\n\002q1\030\005 \001(\002\022\n\n\002q2\030\006" +
      " \001(\002\022\n\n\002q3\030\007 \001(\002\022\013\n\003max\030\010 \001(\002\022\016\n\006unique\030" +
      "\t \001(\r\022\013\n\003top\030\n \001(\t\022\014\n\004freq\030\013 \001(\r\022\014\n\004type" +
      "\030\014 \001(\t\"=\n\014HistResponse\022\r\n\005varId\030\001 \001(\t\022\016\n" +
      "\006strVal\030\002 \003(\002\022\016\n\006sctVal\030\003 \003(\0022\332\002\n\016Summar" +
      "yService\022l\n\nGetSummary\022-.kr.wise.advisor" +
      ".prepare.summary.TableRequest\032-.kr.wise." +
      "advisor.prepare.summary.SummaryReply\"\000\022l" +
      "\n\014GetHistogram\022+.kr.wise.advisor.prepare" +
      ".summary.ColRequest\032-.kr.wise.advisor.pr",
      "epare.summary.HistResponse\"\000\022l\n\rGetBoxOu" +
      "tlier\022+.kr.wise.advisor.prepare.summary." +
      "ColRequest\032,.kr.wise.advisor.prepare.sum" +
      "mary.BoxResponse\"\000B8\n$kr.wise.advisor.pr" +
      "epare.summary.grpcB\016SummaryProcessP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_kr_wise_advisor_prepare_summary_TableRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_kr_wise_advisor_prepare_summary_TableRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kr_wise_advisor_prepare_summary_TableRequest_descriptor,
        new java.lang.String[] { "TableName", "TgtDbms", });
    internal_static_kr_wise_advisor_prepare_summary_ColRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_kr_wise_advisor_prepare_summary_ColRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kr_wise_advisor_prepare_summary_ColRequest_descriptor,
        new java.lang.String[] { "TableName", "ColName", "VarId", "TgtDbms", });
    internal_static_kr_wise_advisor_prepare_summary_TargetDbms_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_kr_wise_advisor_prepare_summary_TargetDbms_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kr_wise_advisor_prepare_summary_TargetDbms_descriptor,
        new java.lang.String[] { "DbConnTrgId", "DbConnTrgPnm", "DbConnTrgLnm", "DbmsTypCd", "DbmsVersCd", "ConnTrgDbLnkChrw", "ConnTrgLnkUrl", "ConnTrgDrvrNm", "DbConnAcId", "DbConnAcPwd", "DbSchId", "DbSchPnm", "DbSchLnm", });
    internal_static_kr_wise_advisor_prepare_summary_BoxResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_kr_wise_advisor_prepare_summary_BoxResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kr_wise_advisor_prepare_summary_BoxResponse_descriptor,
        new java.lang.String[] { "VarId", "Summary", "OutVal", });
    internal_static_kr_wise_advisor_prepare_summary_SummaryReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_kr_wise_advisor_prepare_summary_SummaryReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kr_wise_advisor_prepare_summary_SummaryReply_descriptor,
        new java.lang.String[] { "Summaries", });
    internal_static_kr_wise_advisor_prepare_summary_Summary_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_kr_wise_advisor_prepare_summary_Summary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kr_wise_advisor_prepare_summary_Summary_descriptor,
        new java.lang.String[] { "Name", "Count", "Mean", "Min", "Std", "Q1", "Q2", "Q3", "Max", "Unique", "Top", "Freq", "Type", });
    internal_static_kr_wise_advisor_prepare_summary_HistResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_kr_wise_advisor_prepare_summary_HistResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_kr_wise_advisor_prepare_summary_HistResponse_descriptor,
        new java.lang.String[] { "VarId", "StrVal", "SctVal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
