// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: summary.proto

package kr.wise.advisor.prepare.summary.grpc;

public interface TableRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kr.wise.advisor.prepare.summary.TableRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string tableName = 1;</code>
   */
  java.lang.String getTableName();
  /**
   * <code>string tableName = 1;</code>
   */
  com.google.protobuf.ByteString
      getTableNameBytes();

  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 2;</code>
   */
  boolean hasTgtDbms();
  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 2;</code>
   */
  kr.wise.advisor.prepare.summary.grpc.TargetDbms getTgtDbms();
  /**
   * <code>.kr.wise.advisor.prepare.summary.TargetDbms tgtDbms = 2;</code>
   */
  kr.wise.advisor.prepare.summary.grpc.TargetDbmsOrBuilder getTgtDbmsOrBuilder();
}
