// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: summary.proto

package kr.wise.advisor.prepare.summary.grpc;

public interface TargetDbmsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:kr.wise.advisor.prepare.summary.TargetDbms)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *DB접속대상ID
   * </pre>
   *
   * <code>string dbConnTrgId = 1;</code>
   */
  java.lang.String getDbConnTrgId();
  /**
   * <pre>
   *DB접속대상ID
   * </pre>
   *
   * <code>string dbConnTrgId = 1;</code>
   */
  com.google.protobuf.ByteString
      getDbConnTrgIdBytes();

  /**
   * <pre>
   *DB접속대상물리명
   * </pre>
   *
   * <code>string dbConnTrgPnm = 2;</code>
   */
  java.lang.String getDbConnTrgPnm();
  /**
   * <pre>
   *DB접속대상물리명
   * </pre>
   *
   * <code>string dbConnTrgPnm = 2;</code>
   */
  com.google.protobuf.ByteString
      getDbConnTrgPnmBytes();

  /**
   * <pre>
   *DB접속대상논리명
   * </pre>
   *
   * <code>string dbConnTrgLnm = 3;</code>
   */
  java.lang.String getDbConnTrgLnm();
  /**
   * <pre>
   *DB접속대상논리명
   * </pre>
   *
   * <code>string dbConnTrgLnm = 3;</code>
   */
  com.google.protobuf.ByteString
      getDbConnTrgLnmBytes();

  /**
   * <pre>
   *DBMS유형코드 (ORA	-ORACLE, SYQ-SYBASEIQ, SYA-SYBASEASE, DB2-DB2, MSQ-MS-SQL, ALT-ALTIBASE, MYS-Mysql)
   * </pre>
   *
   * <code>string dbmsTypCd = 4;</code>
   */
  java.lang.String getDbmsTypCd();
  /**
   * <pre>
   *DBMS유형코드 (ORA	-ORACLE, SYQ-SYBASEIQ, SYA-SYBASEASE, DB2-DB2, MSQ-MS-SQL, ALT-ALTIBASE, MYS-Mysql)
   * </pre>
   *
   * <code>string dbmsTypCd = 4;</code>
   */
  com.google.protobuf.ByteString
      getDbmsTypCdBytes();

  /**
   * <pre>
   *DBMS버전코드
   * </pre>
   *
   * <code>string dbmsVersCd = 5;</code>
   */
  java.lang.String getDbmsVersCd();
  /**
   * <pre>
   *DBMS버전코드
   * </pre>
   *
   * <code>string dbmsVersCd = 5;</code>
   */
  com.google.protobuf.ByteString
      getDbmsVersCdBytes();

  /**
   * <pre>
   *접속대상DB연결문자열
   * </pre>
   *
   * <code>string connTrgDbLnkChrw = 6;</code>
   */
  java.lang.String getConnTrgDbLnkChrw();
  /**
   * <pre>
   *접속대상DB연결문자열
   * </pre>
   *
   * <code>string connTrgDbLnkChrw = 6;</code>
   */
  com.google.protobuf.ByteString
      getConnTrgDbLnkChrwBytes();

  /**
   * <pre>
   *접속대상연결URL
   * </pre>
   *
   * <code>string connTrgLnkUrl = 7;</code>
   */
  java.lang.String getConnTrgLnkUrl();
  /**
   * <pre>
   *접속대상연결URL
   * </pre>
   *
   * <code>string connTrgLnkUrl = 7;</code>
   */
  com.google.protobuf.ByteString
      getConnTrgLnkUrlBytes();

  /**
   * <pre>
   *접속대상드라이버명
   * </pre>
   *
   * <code>string connTrgDrvrNm = 8;</code>
   */
  java.lang.String getConnTrgDrvrNm();
  /**
   * <pre>
   *접속대상드라이버명
   * </pre>
   *
   * <code>string connTrgDrvrNm = 8;</code>
   */
  com.google.protobuf.ByteString
      getConnTrgDrvrNmBytes();

  /**
   * <pre>
   *DB접속계정ID
   * </pre>
   *
   * <code>string dbConnAcId = 9;</code>
   */
  java.lang.String getDbConnAcId();
  /**
   * <pre>
   *DB접속계정ID
   * </pre>
   *
   * <code>string dbConnAcId = 9;</code>
   */
  com.google.protobuf.ByteString
      getDbConnAcIdBytes();

  /**
   * <pre>
   *DB접속계정비밀번호
   * </pre>
   *
   * <code>string dbConnAcPwd = 10;</code>
   */
  java.lang.String getDbConnAcPwd();
  /**
   * <pre>
   *DB접속계정비밀번호
   * </pre>
   *
   * <code>string dbConnAcPwd = 10;</code>
   */
  com.google.protobuf.ByteString
      getDbConnAcPwdBytes();

  /**
   * <pre>
   *DB스키마ID
   * </pre>
   *
   * <code>string dbSchId = 11;</code>
   */
  java.lang.String getDbSchId();
  /**
   * <pre>
   *DB스키마ID
   * </pre>
   *
   * <code>string dbSchId = 11;</code>
   */
  com.google.protobuf.ByteString
      getDbSchIdBytes();

  /**
   * <pre>
   *DB스키마물리명
   * </pre>
   *
   * <code>string dbSchPnm = 12;</code>
   */
  java.lang.String getDbSchPnm();
  /**
   * <pre>
   *DB스키마물리명
   * </pre>
   *
   * <code>string dbSchPnm = 12;</code>
   */
  com.google.protobuf.ByteString
      getDbSchPnmBytes();

  /**
   * <pre>
   *DB스키마논리명
   * </pre>
   *
   * <code>string dbSchLnm = 13;</code>
   */
  java.lang.String getDbSchLnm();
  /**
   * <pre>
   *DB스키마논리명
   * </pre>
   *
   * <code>string dbSchLnm = 13;</code>
   */
  com.google.protobuf.ByteString
      getDbSchLnmBytes();
}
